### ISSUE TITLE
Update theme to be compatible with Alaveteli 0.16

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#310]
https://github.com/mysociety/alaveteli/blob/release/0.16/doc/THEME-ASSETS-UPGRADE.md

**Comment by benrfairless** [comment]
Mind if I give this a shot?

**Comment by benrfairless** [comment]
Sorry to jump in and start playing, but can you peer review? I'm not a developer by nature, so I'm expecting a few mistakes.

Cheers!

**Comment by henare** [comment]
> Sorry to jump in and start playing...

No way, this is awesome! Jumping in is definitely the open source way :smiley: 

I'll comment over on the pull request.
