### ISSUE TITLE
update list of agencies/departments

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#312]

**Comment by kat** [comment]
reviewing/checking -  https://www.righttoknow.org.au/body/list/all

**Comment by kat** [comment]
add agency's new portfolio and any tag/name/description to listing per agency https://www.righttoknow.org.au/admin
then to https://github.com/openaustralia/righttoknow/blob/production/lib/public_body_categories_en.rb
and finally remove old portfolio at righttoknow.org.au listing.

**Comment by kat** [comment]
update: have checked email addresses, FOI and IPS links and parent portfolio tags for  those authorities which are not Departments or Ministers. Next up Departments. 

NB. data.gov.au good source of info - eg ABC FOI page not found undera a search on their own site, but found under data.gov.au listing. However it has not been updated since 12/12/13 and there have been some changes to some sites since then, so not authoritative.

**Comment by kat** [comment]
departments all updated

**Comment by henare** [comment]
Awesome, nice work @kat!

**Comment by kat** [comment]
departments done, but still have ministers and parliamentary secretaries, so nearly , but not quite there.

**Comment by henare** [comment]
Oops, sorry for closing this!

**Comment by kat** [comment]
no probs. Fingers crossed I'll clinch it tomorrow.

**Comment by kat** [comment]
I'm renaming those Ministers whose name has changed and can be reasonably identified as the same, such as 'Minister for Agriculture, Fisheries and Forestry' to 'Minister for Agriculture'. (this is also what I did with departments) BUT after a brief chat with @mlandauer, for the time being, I am leaving the old Minister positions listed and active rather than reclassifying them as defunct. eg. Minister for Deregulation - https://www.righttoknow.org.au/admin/body/show/842

**Comment by kat** [comment]
Using this ministry list http://www.aph.gov.au/About_Parliament/Parliamentary_Departments/Parliamentary_Library/Parliamentary_Handbook/Current_Ministry_List

**Comment by kat** [comment]
Going to try uploading the new ministers/parlimentary secretaries from a csv. see #319

**Comment by henare** [comment]
> Going to try uploading the new ministers/parlimentary secretaries from a csv

Hey @kat, have you tried uploading new ministers/parliamentary secretaries (as opposed to updating existing ones via CSV)?

**Comment by kat** [comment]
I only tried the test not an actual upload, because after I did the test, I was not confident of the process, and did not want to risk removing anything else inadvertently. So no I have not tried uploading anything. If you saying that if I try and upload a couple of updates or new items by CSV that there is no risk anything else will be affected, or that if something goes wrong there is a very up to date back up or that you are confident of the process (or any or all of the above?) then I am happy to give it a go.

**Comment by henare** [comment]
> If you saying that if I try and upload a couple of updates or new items by CSV that there is no risk anything else will be affected...

I can't say there's no risk.

> ...or that if something goes wrong there is a very up to date back up

We have daily back ups but we don't want to be restoring from back up.

> ...or that you are confident of the process...

I'm not, that's why I've been working through it with you and Ben and raising issues upstream related to the usability problems you have encountered.

I think the best way forward is if you share the list you're wanting to upload with me and I'll check it out. How does that sound?

**Comment by kat** [comment]
that update was completed.

**Comment by henare** [comment]
:hibiscus: nice :hibiscus:

**Comment by kat** [comment]
closed with #162 - til next time
