### ISSUE TITLE
Add Australian Government Boards

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#316]
Check to see which of the boards listed here are already on Right To Know and http://www.ausgovboards.gov.au/boards/ and add those that are missing.

**Comment by benrfairless** [comment]
@kat is this something you're working on as part of #312 or #317, or do you mind me cracking on with it?

**Comment by kat** [comment]
assigning to you - go for it :-)

**Comment by benrfairless** [comment]
List of all boards downloaded. Now to go through and contact most of them, as I doubt they have FOI links. Out of curiosity, does anyone have a CSV template so I can upload the changes?

**Comment by benrfairless** [comment]
Hey @kat whats your opinion on boards that are part of an existing Agency? (ACIAR Policy Advisory Council as an example)

We already have ACIAR (https://www.righttoknow.org.au/admin/body/show/691) Do we need a separate listing for the Council?

**Comment by kat** [comment]
Moving your first question to a new issue #319

As to your second point, I think you're on the right track already there - if there's an agency listed like your example then that's going to be where the request should go, so no need to duplicate.

**Comment by henare** [comment]
@brfairless the format is detailed on the upload page https://www.righttoknow.org.au/admin/body/import_csv

Let me know if you need any help with it.

**Comment by kat** [comment]
hey @henare please see Issue #319: Confirm upload with csv works - I definitely need help with it. :-)

**Comment by henare** [comment]
Hey @kat I've finished working on all the CSV import tickets. That's resulted in me opening three tickets upstream.

You mentioned a bunch of icky usability problems, it would be great if you could take another look at CSV uploading and create some upstream issues about the usability problems you find: https://github.com/mysociety/alaveteli/issues

**Comment by benrfairless** [comment]
All Boards have now been uploaded. You can see what ones I've uploaded here: https://www.righttoknow.org.au/body/list/github_316
