### ISSUE TITLE
Remove duplicate listing for Department of Resources Energy and Tourism

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#318]
This agency is listed twice, and no longer exists. Any reason not to remove/delete the duplicate more recent listing and make the original one 'defunct'?

**Comment by kat** [comment]
recent listing https://www.righttoknow.org.au/admin/body/show/1101
original listing https://www.righttoknow.org.au/admin/body/show/791

**Comment by henare** [comment]
Weird. I think what happened is that the name was slightly changed when we were doing the imports that created the duplicate.

I agree. Delete this one (it has no requests): https://www.righttoknow.org.au/admin/body/show/1101 and mark this as defunct: https://www.righttoknow.org.au/admin/body/show/791

**Comment by benrfairless** [comment]
Deleted 1101 and updated 791 :)

On Monday, March 24, 2014, Henare Degan notifications@github.com wrote:

> Weird. I think what happened is that the name was slightly changed when we
> were doing the imports that created the duplicate.
> 
> I agree. Delete this one (it has no requests):
> https://www.righttoknow.org.au/admin/body/show/1101 and mark this as
> defunct: https://www.righttoknow.org.au/admin/body/show/791
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openaustralia/righttoknow/issues/318#issuecomment-38417110
> .

## 

Ben Fairless
ben@fairless.id.au

Sent from my iDevice, please forgive spelling and grammatical errors.

**Comment by kat** [comment]
great thanks!
