### ISSUE TITLE
Can't update existing authorities via CSV

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#320]
As part of #316 I want to update the RTK authorities via CSV, however this doesn't appear to be possible.

The issue I'm getting at the moment is:

`ERROR:  duplicate key value violates unique constraint "index_public_bodies_on_url_name"`

**Comment by henare** [comment]
Your file (https://docs.google.com/a/oaf.org.au/file/d/0B6FvM3R1FeGaZ01OZHdUV3dhOTQ/edit) has the following issues:
- Note: `id` field is ignored - this doesn't do anything so you don't need it (TODO: create upstream issue)
- NULL@NULL won't validate as an email address. If you want to create an authority with no email address I think you need to do it manually

and the real kicker:

You can't change the name of an authority using CSV upload (the matching for updates is done on the name) so you need to revert the names in your file for Australian Postal Corporation and Australia-Thailand Institute.

Make those changes and let me know how you get on. (TODO: create upstream issue about the error encountered above).

**Comment by benrfairless** [comment]
I've made the changes to the Aust. Post and to NULL@NULL and new ones uploaded fine.

**Comment by benrfairless** [comment]
@henare could you check this upload attempt over?

https://drive.google.com/a/openaustralia.org/file/d/0B6FvM3R1FeGaUjVWdWNKaXBWbVE/edit?usp=sharing

Error I get is:

```
Validation failed: Name Name is already taken
```

**Comment by henare** [comment]
I think it's trying to import the first line because you've got the hash at the end, rather than the start of `id#`. Change it to `#id`.

**Comment by benrfairless** [comment]
I've changed that and attempted the re-upload, its still not working :(

**Comment by henare** [comment]
I've raised the first issue upstream: https://github.com/mysociety/alaveteli/issues/1416

**Comment by henare** [comment]
> I've changed that and attempted the re-upload, its still not working :(

Worked for me - I've done that on production.

I'm going to close this issue now. Please open new issues for any other problems you encounter, thanks Ben!
