### ISSUE TITLE
Can't use the downloaded CSV to update authorities

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#321]
Reported by @brfairless in #319, depends on #320 being fixed.

**Comment by benrfairless** [comment]
This is the publicly available list at https://www.righttoknow.org.au/body/all-authorities.csv

Are we sure this is really an issue? For it to work, I assume the all-authorities.csv file would need to be updated with the below headings exactly (which doesn't look nice from an end user perspective):

#id name    request_email   publication_scheme  disclosure_log  home_page   tag_string   notes

**Comment by henare** [comment]
OK we could make the title more about the problem: "Make an easy way for admins to bulk update public bodies"?

However, on reflection CSV might not be the best way to be doing this anyway. It doesn't take long for an Alaveteli instance to get a pretty huge number of authorities.

Can you explain your workflow or rationale that leads you to wanting this feature?

**Comment by benrfairless** [comment]
I'm currently working on #316 and using a spreadsheet to collate the relevant data. I would prefer to just upload that spreadsheet and perform a batch job, rather then update each one individually.

**Comment by henare** [comment]
Thanks Ben, so just a preference for that method, cool.

**Comment by henare** [comment]
Issue opened upstream so I'm closing this one.
