### ISSUE TITLE
Provide a way for users to amend their own Annotations

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#322]
Raised by Locutus Sum at https://www.righttoknow.org.au/request/how_is_australia_being_protected#comment-440

"I would prefer to edit and emend the mistakes in my original annotation but that is not possible."

**Comment by benrfairless** [comment]
Hey @henare wondering if you think this needs to be raised upstream or can be done via our theme?

**Comment by henare** [comment]
Hey mate, you're right. This is core functionality so it needs doing
upstream.

**Comment by benrfairless** [comment]
Raised Upstream
