### ISSUE TITLE
STAGING - Attachments sent via email don't appear

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#327]
When responding to a request in Staging. The email comes through however no attachments are visible.

See example: http://test.righttoknow.org.au/request/quick_request#incoming-5

The raw email contains the attachments: http://test.righttoknow.org.au/admin/request/download_raw_email/5

**Comment by benrfairless** [comment]
This issue only happens on Mac Mail. I'll report this upstream (thanks @henare for the suggestion)

**Comment by henare** [comment]
Closing as this issue has been reported upstream.
