### ISSUE TITLE
RTK Logo in HTML preview doesn't load

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#328]
See: https://www.righttoknow.org.au/request/574/response/1843/attach/html/4/Attachment%20CCAF%20Form.doc.html:

![untitled](https://cloud.githubusercontent.com/assets/6841582/2704678/681021e6-c471-11e3-9cbc-b24dcdb03400.png)

The image which isn't visible is hosted at https://www.righttoknow.org.au/alavetelitheme/images/logo.png

**Comment by henare** [comment]
Fixed. I trashed the attachments cache but it turns out I needed to trash the views cache for this.
