### ISSUE TITLE
Enable features of Alaveteli 0.17 in RTK

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#329]
https://github.com/mysociety/alaveteli/blob/release/0.17/doc/CHANGES.md#version-017

There are 2 features of 0.17 which we currently don't have enabled:
- There is a new form for users to request that a new authority should be added, or to request an update to the contact email used for an authority. Site admins are emailed about these requests, and can resolve them from the admin interface.
- There is some initial support for making a request to multiple authorities at once.

Should we look at enabling these?

**Comment by benrfairless** [comment]
On the first point, it works in staging, just requires a minor tweak to our help page which should take me a minute if no-one minds?

**Comment by benrfairless** [comment]
First part done via #330

**Comment by henare** [comment]
I think the first point seems like a good idea so I've deployed the already merged pull request.

On the second point, I don't think we've ever had a request to contact multiple authorities at once so I don't see why we'd want this right now. I'll close this issue but if you disagree on this point please open a new issue specifically about that feature.

Thanks Ben!
