### ISSUE TITLE
Customise favicon

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#331]

**Comment by kat** [comment]
we already have a custom favicon on righttoknow. Is there something you would like to customise further?  I can see the corners could do with a tidy up :-)
![screen shot 2014-04-25 at 10 17 04 am](https://cloud.githubusercontent.com/assets/95376/2796448/0fbc4290-cc0f-11e3-8cb2-976ed9ac210c.png)

**Comment by benrfairless** [comment]
![rtk favico](https://cloud.githubusercontent.com/assets/6841582/2796471/afc68642-cc0f-11e3-8ce4-9cfa643f0450.png)

**Comment by mlandauer** [comment]
What browser/os are you using?

**Comment by benrfairless** [comment]
MacOS 10.9.2, Safari Version 7.0.3 (9537.75.14) and Firefox 24.0

**Comment by mlandauer** [comment]
Thanks. I can see what you're seeing Ben when I use Safari. There's too
many ways that browsers pick up favicons so I imagine it's just a small
tweak to get this fixed.

**Comment by henare** [comment]
I also see that which is why I opened the issue.

The page contains `<link href="/assets/favicon-c2e80544eb3a1fb6b8bfa4b8e4f72899.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />` and that links to the wrong icon https://www.righttoknow.org.au/assets/favicon-c2e80544eb3a1fb6b8bfa4b8e4f72899.ico

**Comment by benrfairless** [comment]
I can’t see the RTK icon in the assets I moved as  part of the theme upgrade. Where is that stored?

**Comment by mlandauer** [comment]
Check out this commit:
https://github.com/openaustralia/alaveteli/commit/9cac4f2387416b5da77a4d5bbe7e21f937cf9129

**Comment by mlandauer** [comment]
I'm confused. No doubt in my case and @kat it's working because the favicon is cached. Now the thing that doesn't make sense to me is I can't find a trace of it in our theme. Very weird.

**Comment by kat** [comment]
I'll find it, fix up and attach to this issue.

**Comment by kat** [comment]
Here's one
![rtk_square_icon_plain](https://cloud.githubusercontent.com/assets/95376/2797153/b0af01de-cc22-11e3-98f0-4b65a1eb1e20.png) (I can't upload the .ico file here so emailing to contact@rtk)

**Comment by benrfairless** [comment]
I'm at work at the moment, but I'll see if I can get this working tonight.... Leave it with me.

**Comment by kat** [comment]
Nice one. thanks Ben

**Comment by benrfairless** [comment]
I've tested this, and it appears this is working. Can someone double check?

**Comment by kat** [comment]
not appearing for me, will try restarting.

kat@oaf.org.au
Founder, Director, Worker OpenAustralia
Foundationhttp://openaustraliafoundation.org.au/
openaustralia.org | planningalerts.org.au | electionleaflets.org.au |
righttoknow.org.au

**Comment by mlandauer** [comment]
@kat I'm guessing you can't see it because it hasn't been deployed to
production yet

**Comment by kat** [comment]
yay! it has appeared. thank you :-)

kat@oaf.org.au
Founder, Director, Worker OpenAustralia
Foundationhttp://openaustraliafoundation.org.au/
openaustralia.org | planningalerts.org.au | electionleaflets.org.au |
righttoknow.org.au
