### ISSUE TITLE
Enable Support for requests to Multiple Authorities

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#332]
From #329 this is a feature in 0.17 which would be useful when trying to request, as an example, Incoming Govt. Briefs (or other types of documents which may be held by different departments, such as PCI Compliance).

 As an example, MJ had to create 8 separate requests to 8 different departments:
https://www.righttoknow.org.au/user/mj

**Comment by henare** [comment]
Great example @brfairless!

What do the rest of you think @openaustralia/team-right-to-know

**Comment by mlandauer** [comment]
I guess my feeling is to err on the side of caution. There's clearly a use
case for it but I don't necessary feel it applies to enough people to
warrant the risk which is that we get accused of aiding the spamming of
agencies.

I feel like they're actively looking for reasons not to respond to FOI
requests from righttoknow. This feels like giving them potentionally a bit
too much ammunition.

However having said all that we should look at this again soon or if a
particular case comes up where the feature might be useful.

Matthew

**Comment by benrfairless** [comment]
@mlandauer the feature requires 2 steps to be enabled - Modification of the Config File followed by enabling it per user on the admin console.

If we change the config file now, it's then a much smaller change to enable it for the users who may need it.

**Comment by mlandauer** [comment]
@bfairless that sounds good to me! :-)

**Comment by benrfairless** [comment]
@henare would you be able to modify the General.Yml file in alaveteli/config to include the below line for the server changes:

```
# Allow some users to make batch requests to multiple authorities. Once
# this is set to true, you can enable batch requests for an individual
# user via the user admin page.

ALLOW_BATCH_REQUESTS: true
```

**Comment by henare** [comment]
Done :sparkles:
