### ISSUE TITLE
Allow Requests to be sent for IC Review

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#336]
Break #99 apart into a few manageable pieces.

When an applicant has exhausted their Internal Review options, the applicant has the right to escalate to the Information Commissioner for review. How should Right to Know handle this?

**Comment by benrfairless** [comment]
@henare @mlandauer does your objection to AAT reviews in #337 also apply to IC reviews?

**Comment by henare** [comment]
Yes for me.

**Comment by mlandauer** [comment]
Me too

**Comment by benrfairless** [comment]
In that case, let's close it :)
