### ISSUE TITLE
AAT Reviews and RTK

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#337]
From #99 

After IC Review, an applicant can appeal to the AAT.

AAT Guidelines on their website: http://www.aat.gov.au/ApplyingForAReview/WhenCanTheAATHelp.htm

```
If you write us an application letter, it must include:
- your name, address and telephone number
- the date you received the decision, and
- brief reasons why you think the decision is wrong.

If you can't give us a copy of the decision, then include in your letter:
the name of the person or organisation that made the decision, and
a brief description of the decision.
```

Issues at hand:
- [ ] Application Fee is $816 for FOI decisions
- [ ] You need to provide rather personal info to get this reduced - http://www.aat.gov.au/FormsAndFees/Fees.htm
- [ ] Is this something we will encounter on a regular basis?

**Comment by henare** [comment]
I vote not to include these kind of reviews. I like how Right To Know is simple and focussed on doing one thing well - the initial FOI requests (and internal review, which is arguably part of that initial process).

**Comment by mlandauer** [comment]
I agree with @henare

**Comment by benrfairless** [comment]
OK, on that basis I'll close this.
