### ISSUE TITLE
Annotations are not word-wrapping correctly.

### ISSUE THREAD

**Issue by fuzzyroddis** [openaustralia/righttoknow#342]
See: https://www.righttoknow.org.au/request/mygov_privacy_impact_assessment#comment-505

![screen shot](https://cloud.githubusercontent.com/assets/2271265/2943572/e736b8f4-d9c5-11e3-9a43-b7b4e723be83.png)

**Comment by fuzzyroddis** [comment]
I have a gut feeling the spaces between the words in the first line are not `0x20` but `U+C2A0`. I copied it out of a PDF.

**Comment by henare** [comment]
Thanks for the issue report!

This could be related to #311

**Comment by fuzzyroddis** [comment]
@henare Do you have an example of an affected blog post?

**Comment by fuzzyroddis** [comment]
As I suspected!
![screen shot](https://cloud.githubusercontent.com/assets/2271265/2943927/ac829b8c-d9cb-11e3-9760-a8572d4dbc35.png)

**Comment by benrfairless** [comment]
@StevenRoddis The entire blog I'm afraid isn't working - https://www.righttoknow.org.au/blog. I think that @henare is suggesting we need to upgrade Ruby to the latest version to fix this.

**Comment by fuzzyroddis** [comment]
I'm not sure upgrading Ruby will fix the issue I reported, I suspect upstream should implement a filter  to convert `U+C2A0` into `U+0020` (which is a regular space)

**Comment by benrfairless** [comment]
Raised Upstream: https://github.com/mysociety/alaveteli/issues/2226
