### ISSUE TITLE
STAGING - Contact Form is Broken

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#348]
When attempting to use the contact form in staging, I get the below response:

```
Sorry, there was a problem processing this page

You have found a bug. Please contact us to tell us about the problem
Technical details

NoMethodError

undefined method `empty?' for nil:NilClass
```

**Comment by henare** [comment]
Nice catch!

App backtrace:

```
A NoMethodError occurred in help#contact:

  undefined method `empty?' for nil:NilClass
  app/controllers/help_controller.rb:76:in `catch_spam'
```

**Comment by henare** [comment]
It's because we're missing a field in our theme: https://github.com/openaustralia/alaveteli/blob/56692a92463c37eaddde7c712a182f1ee8000421/app/views/help/contact.html.erb#L68-L71

**Comment by benrfairless** [comment]
Is there any real difference between Alaveteli base and our themes?

Edit: I can't find one - Should we simply nuke our contact form and use the one in Alaveteli code (instead of our theme)
