### ISSUE TITLE
Remove pages that aren't different from upstream

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#349]
It's worth doing this as we start to get the benefits of improvements and fixes from upstream, e.g. there was both an improvement and bugfix on the contact page we got as part of #348.

**Comment by benrfairless** [comment]
I'll work on this tonight

**Comment by henare** [comment]
:sparkling_heart:

**Comment by benrfairless** [comment]
I've started work on this in https://github.com/openaustralia/righttoknow/tree/issue-349

**Comment by benrfairless** [comment]
will be fixed by #353
