### ISSUE TITLE
Email Disclaimer is too long

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#352]
Current Email Disclaimer looks like this:

<i>Please use this email address for all replies to this request:
[FOI Request Address] @righttoknow.org.au

<i>Is [FOI Contact Address] the wrong address for Freedom of Information requests to Right to Know? If so, please contact us using this form:
http://test.righttoknow.org.au/change_request/new?body=rtk

<i>Write your response as plain text. Only send PDF documents as a last resort. Government guidelines make it clear that PDF is not an acceptable format for you to use in the delivery of government information.
http://test.righttoknow.org.au/help/officers#pdf

<i>This request is being made by an individual using the Right to Know website. The unique email address provided by the service for this request satisfies s.15(2)(c) of the Freedom of Information Act.

<i>Disclaimer: This message and any reply that you make will be published on the internet. Our privacy and copyright policies:
http://test.righttoknow.org.au/help/officers

<i>If you find this service useful as an FOI officer, please ask your web manager to link to us from your organisation's FOI page.

---

This can (and should) be reduced where possible

**Comment by benrfairless** [comment]
I'm considering migrating the files from https://github.com/mysociety/alaveteli/tree/master/app/views/outgoing_mailer to https://github.com/openaustralia/righttoknow/tree/production/lib/views/outgoing_mailer to be able to manipulate the files more, but this would go against the idea of #349

**Comment by henare** [comment]
> I'm considering migrating the files from https://github.com/mysociety/alaveteli/tree/master/app/views/outgoing_mailer to https://github.com/openaustralia/righttoknow/tree/production/lib/views/outgoing_mailer to be able to manipulate the files more, but this would go against the idea of #349

If you need to so we can customise the files then do it and if you don't...don't! :)

The idea is to have as few customisations as possible but that shouldn't get in the way of customising the things we want to.

**Comment by benrfairless** [comment]
PR has been closed with no changes. The disclaimer has everything it needs to for the time being and won't be changing.
