### ISSUE TITLE
STAGING - Logo is covered by the Nav Bar

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#357]
After deploying #353 the RTK logo is hidden by the Navigation bar:

![1](https://cloud.githubusercontent.com/assets/6841582/3280349/1adbfbe8-f45a-11e3-841e-c2ec204e1ac9.PNG)

**Comment by benrfairless** [comment]
This file would look to be the culprit:
https://github.com/openaustralia/righttoknow/blob/f4da37993b9c91c5c974b15f07fe779c8d530a3f/lib/views/general/_topnav.html.erb

The Core (currently active) file is here:
https://github.com/openaustralia/alaveteli/blob/production/app/views/general/_topnav.html.erb

**Comment by benrfairless** [comment]
The fix will be to restore this file: https://github.com/openaustralia/righttoknow/blob/f4da37993b9c91c5c974b15f07fe779c8d530a3f/lib/views/general/_topnav.html.erb

I'll do this tonight.

**Comment by benrfairless** [comment]
Over to @henare to deploy to staging

**Comment by henare** [comment]
Done.
