### ISSUE TITLE
Attention Requested emails aren't received

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#358]
We had 3 attention requested alerts in the console today, but I didn't receive any of them:

https://www.righttoknow.org.au/request/the_mdba_fact_sheet_all_about_th
https://www.righttoknow.org.au/request/the_mdba_fact_sheet_all_about_th_3
https://www.righttoknow.org.au/request/the_mdba_fact_sheet_all_about_th_2

However I get admin attention required emails when I send them from my account.

**Comment by henare** [comment]
I simply cannot reproduce this issue no matter what I try.

I'm going for group therapy: https://groups.google.com/forum/#!topic/alaveteli-dev/V3rFMaxuLb0

**Comment by benrfairless** [comment]
This was caused by the emails being incorrect classed as Spam I think, and was resolved by turning off spam protection on contact@righttknow. I wonder if we have white listed our outbound mail hosts in GApps - https://support.google.com/a/answer/60751?hl=en

**Comment by henare** [comment]
> This was caused by the emails being incorrect classed as Spam I think, and was resolved by turning off spam protection on contact@righttknow.

How did we do that?

> I wonder if we have white listed our outbound mail hosts in GApps - https://support.google.com/a/answer/60751?hl=en

Yes, we do.

It would be awesome if you could update that Alaveteli thread @brfairless.

**Comment by benrfairless** [comment]
> How did we do that?

You made me a manager on the Google Group, and I disabled Spam via the Google Groups page

> It would be awesome if you could update that Alaveteli thread

Awesomeness Achieved :tada:

**Comment by henare** [comment]
> You made me a manager on the Google Group, and I disabled Spam via the Google Groups page

My, my. I didn't know you could do that.

> Awesomeness Achieved :tada: 

Legend :metal:
