### ISSUE TITLE
Explain :display_status with :described_state in request api/advanced search docs

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#361]
It took me a little while to work out the relationship between `:described_state` and `:display_status` in the json versions of requests. Am I right that `:display_status` is just a human friendly version of `:described_state` ?

It could be good to add this information to the [Table of statuses](https://www.righttoknow.org.au/advancedsearch#statuses) so it's explicit.

Maybe that's not the best place for it–would it be suitable to have a full table of every attribute in the json versions? I feel like this would help me as a user of the api. I'm happy to do some work on it if others feel this would be helpful, and with a bit of an explanation or point in the right direction about what each attribute is. Maybe just a link over to http://alaveteli.org/docs/running/states/ for starters.

or it could be added to that table of statuses.

**Comment by equivalentideas** [comment]
Also, are their requests in the system with the [full range of states available in Alaveteli](https://github.com/mysociety/alaveteli/blob/rails-3-develop/app/models/info_request.rb#L95-L110)?

```
        'waiting_response',
        'waiting_clarification',
        'gone_postal',
        'not_held',
        'rejected', # this is called 'refused' in UK FOI law and the user interface, but 'rejected' internally for historic reasons
        'successful',
        'partially_successful',
        'internal_review',
        'error_message',
        'requires_admin',
        'user_withdrawn',
        'attention_requested',
        'vexatious',
        'not_foi'
```

**Comment by benrfairless** [comment]
Answer to 2nd question - List of number of requests in each state:
![states](https://cloud.githubusercontent.com/assets/6841582/3746462/b4ad9e9c-17bf-11e4-90c4-a111cc4d2bd4.PNG)

**Comment by equivalentideas** [comment]
Thanks for that @brfairless

**Comment by benrfairless** [comment]
Just a heads up that you can't view requests marked `:not_foi` and `:vexatious` unless you are either an Admin or the original requester.

**Comment by benrfairless** [comment]
Code for the Advanced Search is here: https://github.com/mysociety/alaveteli/blob/master/app/views/general/_advanced_search_tips.html.erb (We don't use a custom set of search tips in our instance).

**Comment by equivalentideas** [comment]
Thanks thats helpful context.

Know what is that :not_foi state for?

**Comment by benrfairless** [comment]
It looks like `:display_status` can be different from `:described_state`. If you look at this request (https://www.righttoknow.org.au/request/documents_relating_to_the_appoin) `:display_status = "Long Overdue"` (a calculation made by Right to Know based on the time it has been in the Described State) while `:described_state = "waiting_response"`.

Does that help?

**Comment by equivalentideas** [comment]
Yeah, I noticed that on my side, but every request with the described_state "waiting_response" has "Long Overdue" was the display_status—so I assumed that was the designated 'display' version of that 'state'.

This is a bit of a doozy. I think it would make a worthwhile addition to rtk docs or upstream if we can get to the bottom of it. Do you recon it's worth leaving an issue up there?

**Comment by benrfairless** [comment]
`:not_foi` is used by Administrators to hide requests which are clearly not FOI requests.

**Comment by benrfairless** [comment]
This request isn't "Long Overdue": https://www.righttoknow.org.au/request/it_network_documentation_ipv4v6_20.json

**Comment by benrfairless** [comment]
As we don't change anything from a statuses point of view I would suggest this go Upstream. But `:display_state` is different to `:described_state` as I've indicated above ;)

What does everyone else think?

**Comment by equivalentideas** [comment]
Nice, that's great @brfairless .

Do :not_foi come through the api/if I want to hide them as well will I have to handle it on my end?

**Comment by benrfairless** [comment]
It's an interesting status. If I just change the request to not_foi it is still visible. But if I use the admin function "This is not an FOI request" then it sets the visibility to "requester only" and then changes the status.

**Comment by benrfairless** [comment]
@equivalentideas did you want to raise an upstream issue or shall I?

**Comment by equivalentideas** [comment]
I can take it. I'll drop the link back here so you can jump in if you want.

**Comment by benrfairless** [comment]
Awesome. I'll close this then.
