### ISSUE TITLE
/help/about Updates - ACT Requests

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#363]
Master issue: #17  

Issue to discuss changes required to https://www.righttoknow.org.au/help/about in order to allow us to import ACT authorities.

File to change is located here: https://github.com/openaustralia/righttoknow/blob/production/lib/views/help/about.html.erb

**Comment by benrfairless** [comment]
Proposed Change to "What is Right To Know for?":

Old:

> To help you find out inside information about what the Australian government is doing.

Proposed:

> To help you find out information about what the Australian Federal and ACT government is doing.

**Comment by benrfairless** [comment]
Proposed Change to "Why would the public authority bother to reply?":

Old:

> Under the [Freedom of Information Act 1982](http://www.comlaw.gov.au/Current/C2013C00242), or FOI for short, all public authorities have to respond. The response will either contain the information you want, or give a valid legal reason why it must be kept confidential.

Proposed:

> Under Freedom of Information (FOI) laws, almost all public authorities have to respond. The response will either contain the information you want, or give a valid legal reason why it must be kept confidential.

**Comment by henare** [comment]
Thanks for all your work on this and #364 @brfairless. All the generalised bits are now deployed, woo! :rocket: 

I've split the ACT specific stuff out into issues we can address just before we deploy ACT, e.g. #399
