### ISSUE TITLE
/help/requesting Updates - ACT Requests

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#364]
Master Issue #17 

Page is here: https://www.righttoknow.org.au/help/requesting

Code is here: https://github.com/openaustralia/righttoknow/blob/production/lib/views/help/requesting.html.erb

**Comment by benrfairless** [comment]
Updates to "I'm not sure which authority to make my request to, how can I find out?":

[Current](https://github.com/openaustralia/righttoknow/blob/production/lib/views/help/requesting.html.erb#L42-L44):

> Don't worry excessively about getting the right authority. If you get it wrong, they will [transfer your request to the correct authority](http://www.oaic.gov.au/publications/guidelines/Part3_processing_requests_for_access.html#_Toc299022275) for you.

Proposed:

> Don't worry excessively about getting the right authority. If you get it wrong, they should either transfer your request to the correct authority or advise you on the best authority to direct your request.

**Comment by benrfairless** [comment]
[Current](https://github.com/openaustralia/righttoknow/blob/production/lib/views/help/requesting.html.erb#L58):

> See the Information Commissioner's Guidelines [Right of Access](http://www.oaic.gov.au/publications/guidelines/Part3_processing_requests_for_access.html#_Toc299022249) for more.

Proposed:
Remove this line from the Help Files

**Comment by benrfairless** [comment]
[Current](https://github.com/openaustralia/righttoknow/blob/production/lib/views/help/requesting.html.erb#L65-L67):

> At the moment we aim to cover all Australian Federal public authorities. We plan to add State and Local Government authorities soon.

Proposed:

> At the moment we aim to cover the Australian Federal Government and the ACT Government. We plan to add other State and Local Government authorities soon.

**Comment by benrfairless** [comment]
[Current](https://github.com/openaustralia/righttoknow/blob/production/lib/views/help/requesting.html.erb#L81-L87):

> Right To Know lets you make requests for information to a range of organisations:
> - Those formally subject to the Freedom of Information Act
> - Those which choose to voluntarily comply with the Freedom of Information Act
> - Those which aren't subject to the Act but we think should be, on grounds such as them having significant public responsibilities.
> 
> In the last case, we're using the site to lobby for expansion of the scope of the Freedom of Information Act. Even if an organisation is not legally obliged to respond to a Freedom of Information request, they can still do so voluntarily.

Proposed:

> Right To Know lets you make requests for information to a range of organisations:
> - Those formally subject to the FOI Laws
> - Those which choose to voluntarily comply with FOI Laws
> - Those which aren't subject to FOI laws but we think should be, on grounds such as them having significant public responsibilities.
> 
> In the last case, we're using the site to lobby for expansion of the scope of Freedom of Information laws. Even if an organisation is not legally obliged to respond to a Freedom of Information request, they can still do so voluntarily.

**Comment by kat** [comment]
I think explicitly talking about lobbying this way is a mischaracterisation. Let's change this back and keep the primary mission clear :-)

**Comment by henare** [comment]
@kat I was surprised to learn that's what we have [on the site currently](https://www.righttoknow.org.au/help/requesting#authorities).

Can you please open a new issue for this?
