### ISSUE TITLE
Update to 0.19

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#365]
https://github.com/mysociety/alaveteli/blob/release/0.19/doc/CHANGES.md#version-019
## Upgrade Notes
- Ubuntu Precise users can get an updated version of pdftk from mySociety's PPA

Install the repo and update the sources:

```
apt-get install python-software-properties
add-apt-repository ppa:mysociety/alaveteli
apt-get update
```

The mySociety pdftk package (`1.44-7~precise1ms1`) should now be the install
candidate:

```
apt-cache policy pdftk
```
- Install `lockfile-progs` so that the `run-with-lockfile` shell script can be
  used instead of the C program
- Use responsive stylesheets in `config/general.yml`:  
  `RESPONSIVE_STYLING: true`
- Allow access to public body stats page if desired in `config/general/yml`:  
  `PUBLIC_BODY_STATISTICS_PAGE: true`
- Run migrations to define track_things constraint correctly (Robin Houston) and
  add additional index for `event_type` on `info_request_events` (Steven Day)
- The `SHARED_DIRECTORIES` setting now includes `tmp/pids`. The notes below for
  updating the log directory should cover the update steps for `tmp/pids`.
- Capistrano now creates `SHARED_PATH/tmp/pids` and links `APP_ROOT/tmp/pids`
  here, as the alert tracks daemon writes its pids to the generally expected
  location of `APP_ROOT/tmp/pids`.
- rails-post-deploy no longer handles linking `APP_ROOT/log` to a log directory
  outside the app. Capistrano users will find that `:symlink_configuration` now
  links `APP_ROOT/log` to `SHARED_PATH/log`. Users who aleady use the
  `SHARED_FILES` and `SHARED_DIRECTORIES` settings in `config/general.yml`
  should add `log/` to the `SHARED_DIRECTORIES` setting. The existing mechanism
  for shared directories (in `script/rails-deploy-before-down`) will create the
  necessary link to `SHARED_FILES_PATH/log`. If your existing shared log
  directory is not at `SHARED_FILES_PATH/log`, move the directory and re-run
  `script/rails-post-deploy` to link up the new location. If you don't use
  `SHARED_FILES` and `SHARED_DIRECTORIES`, alaveteli will now write it's
  application logs to `APP_ROOT/log` rather than `APP_ROOT/../logs` by default.
- `public_body_change_requests/new.html.erb` has a new field for spam prevention
  so customisations of this template should be updated with:
  
    <p style="display:none;">
      <%= label_tag 'public_body_change_request[comment]', _('Do not fill in this field') %>
      <%= text_field_tag 'public_body_change_request[comment]' %>
    </p>
  This is the anti-spam honeypot.
-  The workaround for an old [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=637239) in libc6 in squeeze has been removed. If you're running on squeeze, please make sure you're using the latest version of libc6 (2.11.3-4) to prevent the risk of segfaults.
- The capistrano `stop`, `start` and `restart` tasks now restart the app
  server via the service `/etc/init.d/alaveteli`. If you're using
  capistrano for deployment, make sure `/etc/init.d/alaveteli` exists
  and is current, and executable by the cap user. You can create it using the template
  `config/sysvinit-thin.ugly` or `config/sysvinit-passenger.ugly` as
  described in http://alaveteli.org/docs/installing/manual_install/#generate-alaveteli-service

**Comment by henare** [comment]
> The capistrano stop, start and restart tasks now restart the app server via the service /etc/init.d/alaveteli

I've modified our init script so that it does nothing on `start` and `stop` (since you don't need that with Passenger) and so that `restart` will restart both staging and production since we can't tell from the deploy which one it wants to restart.

The full script is in this gist: https://gist.github.com/henare/4daaa7364bd8eedfd8ac

**Comment by henare** [comment]
Merging the latest 0.19 tag into staging caused merge conflicts so I used `git merge -X theirs 0.19.0.13` to accept upstream's changes by default. This appears to have worked:

https://github.com/openaustralia/alaveteli/compare/staging...mysociety:hotfix/0.19.0.13

Since tests passed and it looks OK on my development machine I'm deploying to staging.

**Comment by henare** [comment]
I've deployed to staging and it looks good to me. The init script worked as expected on deploy.

@brfairless can you poke around and try to break things? http://test.righttoknow.org.au/

If you get a chance this evening I think we'll be good to deploy to production in the morning.

**Comment by benrfairless** [comment]
We can:
- Make a Request
- Annotate a request
- Reply to a Request
- Request an authority update
- decline an authority update

I think this is pretty much done and ready to go!

**Comment by henare** [comment]
Thanks for your testing @brfairless! :sparkles: 

This is now deployed :shipit:
