### ISSUE TITLE
"I've been asked to pay" status

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#366]
When you get a response from an authority, RTK asks you what the status of your request is and promises that we'll tell you what to do next. However when you've been asked to pay something, none of the statues we offer quite fit and you're certainly not told what to do next.

What if we added a status, even a dummy one, that at least gives you some hints on what to do if you've been asked to pay? Things like asking for a reduction in charges, how you can generally pay, crowd funding, etc.

**Comment by benrfairless** [comment]
:+1:  Sounds like a good idea! I'm sure its possible, but need to read into figure out how

**Comment by equivalentideas** [comment]
I think this is a good idea, it would be useful on the Detention Logs side to group by status and see what needs payment for the project.

## 

Luke Bacon

http://equivalentideas.com

http://twitter.com/equivalentideas

+61 406566693

**Comment by benrfairless** [comment]
Do we still think this should be added? If so, I'll start working on it (probably next weekend at this point).

**Comment by henare** [comment]
> Do we still think this should be added?

I think there's still some good ideas here to be explored.

> If so, I'll start working on it (probably next weekend at this point).

We need to think about how this would work first so if you want to work on it, don't look at the code but instead map out how it will work. We can then all review that and then move on to engineering once we're agreed on a solution or way forward.

I hope that makes sense :)

**Comment by benrfairless** [comment]
It could work in a similar way to how failed requests work. When you select a status which indicates the request has failed, it redirects you to http://www.righttoknow.org.au/help/unhappy/ which provides advice on some next steps.

Some of the things we could mention are RE: being asked to pay include:
- Reduction on Public Interest Grounds
- Clarifying the request - Removing Drafts/Duplicates
- Raising the money via Pozible or other crowd funding
- Going to twitter to ask for help, or asking for help on the site

What do you think?

**Comment by henare** [comment]
I've had a bit more of a think about this and discussed it with @equivalentideas.

This feature could be really useful in a lot of places so upstream might be interested in it. How about we email the list and see if anyone else is interested in this feature and if so we can open an issue/pull request on Alaveteli?

**Comment by benrfairless** [comment]
I'll email the group later today and see if anyone else would find this useful.

**Comment by henare** [comment]
Reopen if any else would find this useful.
