### ISSUE TITLE
Gmail addresses don't work with the contact form

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#367]
When sending a contact form from an @gmail.com address, the form is not received by contact@

This doesn't affect Google hosted services (Google for Work)

Tested with 2x seperate email addresses whilst logged in and as a guest on the site.

**Comment by benrfairless** [comment]
I suspect this is caused by a spam prevention measure in the contact@ Google group. I'm not sure if we could engage Google to check spam prevention on their end?

**Comment by henare** [comment]
Groups Admin had 15 pending messages. I've allowed them and they've come through.

I don't know why they were held back - the settings look good to me.

**Comment by benrfairless** [comment]
is that something I can get access to that area for the contact group @henare? Would be nice to have for troubleshooting. Worth checking with Google to see if we can disable the "held" feature?

Glad we got most of the messages, will reply to them tonight.

**Comment by benrfairless** [comment]
I've enabled all messages to come through to the group, and will look into it depending on spam levels.
