### ISSUE TITLE
Update (and monitor) external links

### ISSUE THREAD

**Issue by luke-john** [openaustralia/righttoknow#370]
Hi,

After noticing a couple of dead links yesterday, Ben Fairless kindly pointed me to the righttoknow github repo.

I've just run a script to check the status of any links under /lib/views and it looks like theres a number of outdated links.

The links are in the form filename linenumber url status
## Https security certificate expired
- [x] ./lib/views/help/credits.html.erb   42  https://www.accesointeligente.org/  0
  - replacement: http://www.accesointeligente.cl/
  - notes: https://www.accesointeligente.cl/ has certificate error as well.
## Not found
- [x] ./lib/views/help/requesting.html.erb    43  http://www.oaic.gov.au/publications/guidelines/Part3_processing_requests_for_access.html#_Toc299022275  404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-5-exemptions
  - notes: Section 5.41 no longer has a direct link
- [x] ./lib/views/help/requesting.html.erb    58  http://www.oaic.gov.au/publications/guidelines/Part3_processing_requests_for_access.html#_Toc299022249  404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-3-processing-requests-for-access#right
- [x] ./lib/views/help/requesting.html.erb    164 http://www.oaic.gov.au/publications/guidelines/Part4_Charges_for_providing_access.html#_Toc284510873    404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-4-charges-for-providing-access#guiding
- [x] ./lib/views/help/requesting.html.erb    173 http://www.oaic.gov.au/publications/guidelines/Part4_Charges_for_providing_access.html#_Toc284510893    404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-4-charges-for-providing-access#correction
  - notes: Section 4.47
- [x] ./lib/views/help/requesting.html.erb    208 http://www.oaic.gov.au/publications/fact_sheets/FOI_fact_sheet9_expect_agencies_ministers.html#extending_timeframe  404
  - replacement: http://www.oaic.gov.au/freedom-of-information/foi-resources/freedom-of-information-agency-resources/foi-agency-resource-13-extension-of-time-for-processing-requests
  - notes: Potentially different information
- [x] ./lib/views/help/requesting.html.erb    250 http://www.ag.gov.au/www/agd/agd.nsf/Page/Copyright_CommonwealthCopyrightAdministration_StatementofIPPrinciplesforAustralianGovernmentAgencies  404
  - replacement: http://www.oaic.gov.au/information-policy/information-policy-resources/information-policy-agency-resources/principles-on-open-public-sector-information
  - notes: No direct link, Principle 6: Clear reuse rights
- [x] ./lib/views/help/requesting.html.erb    290 http://www.oaic.gov.au/publications/fact_sheets/FOI_fact_sheet5_your_personal_information.html#access   404
  - replacement: http://www.oaic.gov.au/freedom-of-information/foi-resources/freedom-of-information-fact-sheets/foi-fact-sheet-5-your-personal-information
  - notes: No direct link, Accessing your personal information
- [x] ./lib/views/help/privacy.html.erb   63  http://www.oaic.gov.au/publications/guidelines/Part3_processing_requests_for_access.html#_Toc299022262  404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-3-processing-requests-for-access
  - notes: Section 3.39 no longer has a direct anchor. Also quote is incorrect
  - original quote:
    - the FOI Act does not require an applicant to disclose their identity
  - replacement quote:
    -  The FOI Act does not require an applicant who is a natural person to disclose or provide proof of their identity, nor require a body corporate or politic to establish that it is a legal entity. 
- [x] ./lib/views/help/privacy.html.erb   73  http://www.oaic.gov.au/publications/guidelines/Part3_processing_requests_for_access.html#_Toc299022261  404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-3-processing-requests-for-access
  - notes: Section 3.25 no longer has a direct anchor.
- [x] ./lib/views/help/privacy.html.erb   84  http://www.oaic.gov.au/publications/guidelines/Part8_decisions_FOI_requests.html#_Toc306802095  404
  - replacement: http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/part-3-processing-requests-for-access
  - notes: Section 8.102 is now Section 3.177. Section 8.104 is now 3.179 no direct links
  - original quotes:
    - "8.102 Subject to limited exceptions, an applicant who requests access to a document in a particular form has a right to be given access in that form (s 20(2))."
    - "8.104 As agencies and ministers obtain greater access to new technology it is expected that they will make reasonable efforts to facilitate access to documents that have not previously been accessible in a particular form. Wherever possible access to documents by means that do not require physical inspection should be preferred."
  - replacement quotes:
    - "3.177 Subject to limited exceptions, an applicant who requests access to a document in a particular form has a right to be given access in that form (s 20(2))."
    - "3.179 Agencies and ministers are expected to make reasonable use of available technology to facilitate access to documents â for example, by providing copies by electronic transmission, or to provide access in a particular form that is possible only through technology. Access to documents by means that do not require physical inspection in an agency office should generally be preferred."
- [x] ./lib/views/help/unhappy.html.erb   29  http://www.oaic.gov.au/publications/guidelines/guidelines-part9_guidelines-internal-review.html#_Toc287345401   404
  - notes: fixed in #369 
- [x] ./lib/views/help/unhappy.html.erb   42  http://www.oaic.gov.au/publications/guidelines/guidelines-part9_guidelines-internal-review.html#_Toc287345402   404
  - notes: fixed in #369
### Location Changed
- [x] ./lib/views/help/requesting.html.erb    275 http://www.oaic.gov.au/publications/guidelines.html#foi_guidelines  301
- [x] ./lib/views/help/requesting.html.erb    276 http://www.oaic.gov.au/publications/factsheets.html#FOI_factsheets  301
### https redirects
- [x] ./lib/views/help/requesting.html.erb    124 http://wordpress.com/   301
- [x] ./lib/views/help/about.html.erb 50  http://twitter.com/righttoknowau    301
- [x] ./lib/views/help/credits.html.erb   36  http://www.whatdotheyknow.com/help/credits#thanks   301
- [x] ./lib/views/help/credits.html.erb   59  http://www.openaustraliafoundation.org.au/donate/   301
- [x] ./lib/views/help/credits.html.erb   67  http://www.openaustraliafoundation.org.au/volunteer/    301
- [x] ./lib/views/general/_footer.html.erb    5   http://www.openaustraliafoundation.org.au   301
- [x] ./lib/views/help/about.html.erb 46  http://www.openaustraliafoundation.org.au/2012/09/25/accelerating-to-the-future-of-online-democracy-in-australia/   301
- [x] ./lib/views/help/about.html.erb 46  http://www.openaustraliafoundation.org.au/donate/   301
- [x] ./lib/views/help/credits.html.erb   24  http://www.openaustraliafoundation.org.au/2012/09/25/accelerating-to-the-future-of-online-democracy-in-australia/   301
- [x] ./lib/views/help/credits.html.erb   88  http://www.mysociety.org/   301
- [x] ./lib/views/general/frontpage.html.erb  45  http://www.mysociety.org/   301
- [x] ./lib/views/help/credits.html.erb   90  http://open.org.nz  301
- [x] ./lib/views/general/frontpage.html.erb  51  http://open.org.nz  301
- [x] ./lib/views/help/about.html.erb 40  http://www.comlaw.gov.au/Current/C2013C00242    302
- [x] ./lib/views/help/credits.html.erb   65  http://alaveteli.org    302
- [x] ./lib/views/general/_footer.html.erb    18  http://www.alaveteli.org/   301
- [x] ./lib/views/help/credits.html.erb   36  http://www.alaveteli.org/   301
- [x] ./lib/views/help/credits.html.erb   78  http://www.getup.org.au/    302
- [x] ./lib/views/general/frontpage.html.erb  30  http://www.getup.org.au/    302
- [x] ./lib/views/help/credits.html.erb   80  http://newmatilda.com/  302
- [x] ./lib/views/general/frontpage.html.erb  36  http://newmatilda.com/  302

I'm uncertain what sort of infrastructure is being run by openaustralia/righttoknow, but it may be worthwhile to set up a cron job somewhere to periodically scan the website for dead links and post a github issue/ let someone know.

**Comment by luke-john** [comment]
I'll have a look at trying to find replacements for 404's tonight and submit a pull request.

**Comment by luke-john** [comment]
A number of the links no longer have anchors on the sections referred to.

Should I update the link text to include the section code or simply leave as is?

**Comment by benrfairless** [comment]
Thanks for the issue and for identifying all those dead links @lukejohnosmahi!

On the OAIC links, I'm not sure if it's worth updating them at this stage due to the fact that OAIC will not exist from 31 December. I would suggest simply changing the links for those that are valid for now, unless someone else had an idea? ping @openaustralia/team-right-to-know

**Comment by benrfairless** [comment]
On the HTTPS Security Certificate one, the best link would be http://ciudadanointeligente.org would be the best link I think for now.

**Comment by luke-john** [comment]
So for the OAIC links they still have two months where those guidelines are "valid".

At which stage the AG will become the body in charge of providing guidelines, I've contacted the AG to ask if they intend on maintaining the current OAIC guidelines or starting from scratch.  I've created an issue to track this change #371.

I'll submit a separate pull request with the OAIC links updated as I think two months is a long time for users of righttoknow to not have accurate information.

As an aside do you know if the openaustralia foundation has current plans for a site similar to righttoknow but for general correspondence with mps and government authorities?

**Comment by benrfairless** [comment]
Fixed by #381

**Comment by henare** [comment]
On minister's pages we've got out of date links to FOI guidelines at the OAIC too, e.g. https://www.righttoknow.org.au/body/minister_for_communications
