### ISSUE TITLE
Doesn't validate

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#375]
http://validator.w3.org/check?uri=http%3A%2F%2Frighttoknow.org.au%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by benrfairless** [comment]
Full error:

> Error Line 31, Column 118: Bad value https://fonts.googleapis.com/css?family=Maven+Pro:400,700|Actor for attribute href on element link: Illegal character in query: not a URL code point.

**Comment by benrfairless** [comment]
I'm confused by this... On line 31, there is no Column 118! There is only 111 columns
