### ISSUE TITLE
Update Twitter background

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#378]
Update the Twitter background, it's not very nice. Would the top of https://www.righttoknow.org.au/admin/stats look better?

![image](https://cloud.githubusercontent.com/assets/6841582/5718544/9db1515a-9b56-11e4-9160-19c2f2cccf91.jpg)

**Comment by henare** [comment]
> Update the Twitter background, it's not very nice.

I agree.

> Would the top of https://www.righttoknow.org.au/admin/stats look better?

I don't agree ;)

I quite like the concept of using a screenshot of the site but maybe doesn't work here. Or we could include pics of documents released or something?

Maybe @equivalentideas has some thoughts?

**Comment by equivalentideas** [comment]
Could we do something with the data from the sight? Coloured grid for success of requests? something more about the awesome community?

**Comment by henare** [comment]
> something more about the awesome community?

I really like that - maybe a collage of user avatars?

**Comment by benrfairless** [comment]
> I really like that - maybe a collage of user avatars?

That could be quite nice, but would we need our user's approval? I would mock something up, but I'm not really a designer-type

**Comment by henare** [comment]
> That could be quite nice, but would we need our user's approval?

I don't think so - they're publicly available.

**Comment by benrfairless** [comment]
I think we should remove the current background while we decide what we are going to do with this. @henare @mlandauer any objections?

**Comment by henare** [comment]
I've removed it and make our colour match the site.
