### ISSUE TITLE
Re-Enable Spam Protection on contact

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#382]
Due to the increasing rates of spam, I suggest we:
[ ] Change the "Spam Messages" setting in Groups > Manage Group > Settings > Moderation to <i> Send them to the Moderation queue and send notification to moderators </i>
[ ] Add everyone who needs to be alerted to the "Managers" group via Group > Manage Group > Roles > Roles so they receive notifications of spam

This will ensure that selected people can see the spam coming through and can respond to any incorrectly classified spam.

**Comment by henare** [comment]
1. What spam?
2. Given we'll all be notified about pending messages, won't we still be getting a message for each spam message therefore defeating the purpose of this?

**Comment by benrfairless** [comment]
> What spam?

All those people trying to Update the Anzac Centenary Advisory Board

> Given we'll all be notified about pending messages, won't we still be getting a message for each spam message therefore defeating the purpose of this?

I was hoping there would be a way to have it as a daily digest, so we wouldn't have this issue. Alas, Google isn't as nice as they want us.

**Comment by henare** [comment]
> All those people trying to Update the Anzac Centenary Advisory Board

Those emails are from Right To Know - we don't want them marked as spam! :)

**Comment by benrfairless** [comment]
> Those emails are from Right To Know - we don't want them marked as spam! 

But they are being run by spambots, therefore we do want them blocked, no?

**Comment by henare** [comment]
No - the emails are from us.

Instead we need to fix the form so it doesn't get used in that way (which is done in the latest Alaveteli, AFAIK).
