### ISSUE TITLE
Update the signup email policy

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#383]
This should let people know that we will email them occasionally about donations or other things related to improving the project.

**Comment by benrfairless** [comment]
I can work on this tonight if you would like. We can change the wording to:

> When you sign up to Right to Know, we will only send you emails about:
> - requests you have made
> - alerts you have setup
> - Any reason you specifically authorise
> 
> You might also receive the occasional email from the OpenAustralia Foundation (the charity that runs Right to Know) seeking your feedback on Right to Know and other OpenAustralia Foundation projects.

**Comment by benrfairless** [comment]
We should also email our existing users to advise them of changes.

**Comment by equivalentideas** [comment]
What about:

> You will also receive occasional emails from the [OpenAustralia Foundation](https://www.openaustraliafoundation.org.au/), the charity that runs Right to Know. You will be able to opt out from those emails without effecting your Right To Know alerts.

Would be nice to make it a bit friendlier

**Comment by benrfairless** [comment]
I was going to put a bit about opt-out however I wasn't sure if we were going to support opt-out. I'm happy with Luke's change, so the full wording now is:

> When you sign up to Right to Know, we will send you emails about:
> - requests you have made
> - alerts you have setup
> - and for any other reason you specify
> 
> You will also receive occasional emails from the [OpenAustralia Foundation](https://www.openaustraliafoundation.org.au/), the charity that runs Right to Know. You will be able to opt out from those emails without affecting other emails from Right to Know.
> 
> We won't share your email address with anyone else unless you specifically authorise it, or we have to under the law. When you send a request to an authority, they receive an email from a unique @righttoknow.org.au email address.

**Comment by equivalentideas** [comment]
For clarity:

> When you make a request to an authority, they receive an email from a unique @righttoknow.org.au email address, your email address is not revealed.

**Comment by benrfairless** [comment]
Fixed by #385
