### ISSUE TITLE
No Mail Logs visible in Admin

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#386]
It appears that the Mail Logs in the Administrator console are no longer showing up. I can't find any after the 15th. Contrary to what Admin says, we used to see both incoming and outgoing logs.

**Comment by henare** [comment]
I'm seeing mail logs after the 15th. There's some from yesterday on this request for example https://www.righttoknow.org.au/admin/request/show/820

Got an example @brfairless?

**Comment by benrfairless** [comment]
Looks fixed now. Not sure what happened there, or if there is a delay in the logs being available :-)

**Comment by henare** [comment]
They get loaded every hour at [31 minutes past the hour](https://github.com/openaustralia/alaveteli/blob/6d5d1f5618c4c7d297b0373941336f0603635593/config/crontab-example#L20-L21).
