### ISSUE TITLE
Create a "Practical Refusal" category

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#388]
Same as #366 but for practical refusal.

**Comment by henare** [comment]
My first reaction to this was, "let's not clutter the statuses with too many options for people" but on reflection I can see where you're coming from.

When people get a practical refusal it would be great to give them some options. Often agencies do this by all too often they don't.

At the moment our wonderful community often steps in and helps requesters. This is a really nice, personal touch.

Could the solution to this and #366 be to create some really helpful boilerplate for volunteers to add as an annotation to requests where people encounter these statuses?

**Comment by benrfairless** [comment]
@henare you are right. There are a few great people who jump in whenever a request gets too tricky to offer help and advice. That said, there are often differing reasons why a practical refusal reason might exist, and the agencies generally do a poor job on providing guidance. 

They just say "call us and we can help" which removes the transperancy.

We could go down the path of creating a unique help page which would contain some "commonly used jargon" by agencies, which we can then update with advice, or we could create a specific page when they select the category. 

Another option would be a "I need help" button which could flag the request and perhaps post to Twitter/Facebook (from either the RTK account or from a user's own account), but I feel that would be an idea for upstream vs. our theme.

**Comment by henare** [comment]
> We could go down the path of creating a unique help page which would contain some "commonly used jargon" by agencies, which we can then update with advice...

Would it be worth asking Locutus about this given her experience helping people?

> ...or we could create a specific page when they select the category.

Selecting a category sounds like a pain. It's hard enough getting people to categorise requests. Anything we can do to remove extra steps for people is a good thing.

> Another option would be a "I need help" button which could flag the request and perhaps post to Twitter/Facebook (from either the RTK account or from a user's own account), but I feel that would be an idea for upstream vs. our theme.

:heart: I love this idea :heart:

**Comment by benrfairless** [comment]
Raised Upstream: https://github.com/mysociety/alaveteli/issues/2155
