### ISSUE TITLE
2015 Cabinet reshuffle - update list of agencies/ministers

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#389]
Some agencies were abolished recently and there was a cabinet reshuffle. Related to #312

**Comment by kat** [comment]
parliament is sitting again on Feb 9th so would be good to get most of this done by then.

**Comment by henare** [comment]
This could be helpful, it's the changes we had to make on OA.org https://github.com/openaustralia/openaustralia-parser/commit/a1855f29bb88ea6b36114682b0dc97728836e28c

**Comment by kat** [comment]
thanks @henare - if only these could be related _somehow_

**Comment by benrfairless** [comment]
I'm going through off this list provided by the OAIC: https://www.righttoknow.org.au/request/foiable_agencies

I'll create a list of agencies which are on the OAIC list but not in RTK, then I'll compare whats in RTK but not on the OAIC list.

**Comment by benrfairless** [comment]
Changes so far:

> 18:31:37  Wreck Bay Aboriginal Community Council was created/updated by administrator ben_fairless 
> 18:31:37  Workplace Gender Equality Agency was created/updated by administrator ben_fairless 
> 18:31:37  Skills Australia Board was created/updated by administrator ben_fairless 
> 18:31:37  Royal Australian Air Force Welfare Trust Fund was created/updated by administrator ben_fairless 
> 18:31:37  Road Safety Remuneration Tribunal was created/updated by administrator ben_fairless 
> 18:31:37  Parliamentary Secretary to the Minister for the Environment was created/updated by administrator ben_fairless 
> 18:31:37  Parliamentary Secretary to the Minister for Industry was created/updated by administrator ben_fairless 
> 18:31:37  Parliamentary Secretary to the Minister for Finance was created/updated by administrator ben_fairless 
> 18:31:37  Parliamentary Secretary to the Minister for Education was created/updated by administrator ben_fairless 
> 18:31:37  Parliamentary Secretary to the Minister for Communications was created/updated by administrator ben_fairless 
> 18:31:37  Office of the Independent National Security Legislation Monitor was created/updated by administrator ben_fairless 
> 18:31:37  Minister Assisting the Prime Minister for Women was created/updated by administrator ben_fairless 
> 18:31:37  Minister Assisting the Prime Minister for the Public Service was created/updated by administrator ben_fairless 
> 18:31:37  Gene Technology Ministerial Council was created/updated by administrator ben_fairless 
> 18:31:37  Office of Township Leasing was created/updated by administrator ben_fairless 
> 18:31:36  Australian Grape and Wine Authority was created/updated by administrator ben_fairless 
> 18:31:36  Assistant Minister for Social Services was created/updated by administrator ben_fairless 
> 18:31:36  Assistant Minister for Infrastructure and Regional Development was created/updated by administrator ben_fairless 
> 18:01:59  Secretaries’ ICT Governance Board was created/updated by administrator ben_fairless 
> 17:58:09  Royal Australian Air Force Veterans' Residences Trust Fund was created/updated by administrator ben_fairless 
> 17:56:24  Anti-discrimination in Recruitment had an annotation posted by Julie Bingo. 
> 17:53:28  Newman's pension for life had an annotation posted by Julie Bingo. 
> 17:49:43  Parliamentary Secretary for Industry was created/updated by administrator ben_fairless 
> 17:36:48  Australia Council for the Arts was created/updated by administrator ben_fairless 
> 17:35:44  Gene Technology Ethics and Community Consultative Committee was created/updated by administrator ben_fairless 
> 17:34:58  Federal Circuit Court of Australia was created/updated by administrator ben_fairless 
> 17:31:11  Fair Work Commission was created/updated by administrator ben_fairless 
> 17:22:21  Director of National Parks was created/updated by administrator ben_fairless 
> 17:21:39  Committees established under Tradesmen’s Rights Regulation Act 1946 was created/updated by administrator ben_fairless 
> 17:06:13  Asbestos Safety and Eradication Agency was created/updated by administrator ben_fairless

**Comment by benrfairless** [comment]
I just need to remove or defunct the old stuff and we should be done.

**Comment by henare** [comment]
Amazing :star2:

**Comment by henare** [comment]
Is this done?

**Comment by henare** [comment]
Please reopen if this isn't done.
