### ISSUE TITLE
Encourage Agenices to deal with requests informally

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#390]
In the template, we currently provide a Greeting and a salutation, unless it's an Internal review where we provide a bit more information.

Should we add the below (or something like it) to the user editable template on RTK:

> Please deal with this request informally or in accordance with your Administrative Access scheme if practicable. If this isn't practical, please consider it a formal application under the Freedom of Information Act.

**Comment by henare** [comment]
Most of the time it doesn't help asking agencies to do this anyway so I don't think we should add it because it's just more cognitive overhead for the requester.

**Comment by benrfairless** [comment]
All good then, we will close the request :)
