### ISSUE TITLE
update portfolio tags

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#392]
update these portfolio tags 

education-and-training =Education and Training _was_ education=Education
industry-and-science=Industry and Science   _was_ industry=Industry
prime-minister=Prime Minister    _was_ prime_minister_and_cabinet=Prime Minister and Cabinet

**Comment by kat** [comment]
added education_and_training tag to those which were previously tagged education, using search https://www.righttoknow.org.au/admin/body/list?query=education very handy for when, as now, portfolio name changes and holds on to same authorities.

**Comment by benrfairless** [comment]
Hi @kat,

I've got a list of all the portfolios here: https://github.com/openaustralia/righttoknow/blob/60430a6c11ba0915cb8a2a81c9daae0712a0eb02/lib/public_body_categories_en.rb

We had `education_employment_and_workplace_relations`, '`industry_innovation_science_research_and_tertiary_education` and `prime_minister_and_cabinet` as the current ones. 

What I'm assuming you want is to:

Change `education_employment_and_workplace_relations` to `education-and-training`
Change `industry_innovation_science_research_and_tertiary_education` to `industry-and-science`
Change `prime_minister_and_cabinet` to `prime-minister`

I would also suggest adding a `employment` portfolio as we've kinda removed that from the education portfolio. If that's OK, I can work on it tomorrow?

**Comment by kat** [comment]
(see #162 )

**Comment by kat** [comment]
done!

**Comment by henare** [comment]
:tada:
