### ISSUE TITLE
Work out how to neatly display references to the various laws around Australia

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#397]
In some places, mainly the help text, we need to be able to link to the various FOI laws around Australia.

For instance:

> **Why would the public authority bother to reply?**
> Under the [Freedom of Information Act 1982](http://www.comlaw.gov.au/Details/C2015C00013), or FOI for short, all public authorities have to respond. The response will either contain the information you want, or give a valid legal reason why it must be kept confidential. 

At first I thought we might be able to generalise the sentence and remove the references and links to the laws:

> By law, all public authorities have to respond. The response will either contain the information you want, or give a valid legal reason why it must be kept confidential. 

But it turns out it's nice to be able to link to the different legislation because it allows people to learn more if they so choose. This is especially true where we're pointing out a part of the legislation, such as built in transfers between agencies.

I've tried inline...

![selection_002](https://cloud.githubusercontent.com/assets/48945/6386463/fb8133d4-bdcc-11e4-8af8-a4b70586f24b.png)

...and referenced notes...

![selection_001](https://cloud.githubusercontent.com/assets/48945/6386462/fb7db27c-bdcc-11e4-8384-cbf1e9e6eadb.png)

...but they both feel cluttered and unwieldy when you add all the jurisdictions.

One other idea could be a superscripted note that then has a popup with the links in it but immediately that sounds like it has accessibility problems.

**Comment by benrfairless** [comment]
I think the way we have done it for the ACT changes (https://www.righttoknow.org.au/help/requesting#ico_help) is a brilliant way of doing it. We make it clear that Right to Know will handle most things, but if they want to review the law provide it to them!

**Comment by henare** [comment]
Right on! :+1:
