### ISSUE TITLE
federal authority pages broken on staging branch

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#402]
When I select a Federal Authority from its name on this page http://test.righttoknow.org.au/body/list/federal on the staging branch I get the following error.

Sorry, there was a problem processing this page

You have found a bug. Please contact us to tell us about the problem
Technical details

NoMethodError

undefined method `[]' for nil:NilClass

This is one of the ones I just uploaded.

**Comment by henare** [comment]
A category description is mandatory so I've added this now.
