### ISSUE TITLE
tag appears as authority name in staging branch

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#403]
recently uploaded list of federal agencies threw up tag this as an authority

 health foi_yes federal minister directory_gov_au oaic_report_2011_2012 github_316 

it's the last entry in the [list of Ministers](http://test.righttoknow.org.au/body/list/minister)

**Comment by benrfairless** [comment]
I think something has broken while doing the uploads via CSV, as that authority doesn't appear to have been created properly (also explains #402). I think this is going to be something on the staging server we need to address...

**Comment by kat** [comment]
my bad. Fixed now.
