### ISSUE TITLE
Changes in Staging don't reflect what's in Github

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#405]
There are category changes in Staging which don't mirror up with what I see in Github. I'm not sure if this is causing issues with the authorities issues which have been raised in staging.

**Comment by henare** [comment]
@kat and I [are testing](https://oaf.slack.com/archives/hackerspace/p1425020890000260) another [branch](https://github.com/openaustralia/righttoknow/tree/category-changes).
