### ISSUE TITLE
Change preview bar

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#406]
The preview as HTML bar doesn't show the logo well. We should change the top bar to be a different colour (probably the same blue as the background)

**Comment by equivalentideas** [comment]
Could you please add a screen shot of what you mean? @brfairless

**Comment by benrfairless** [comment]
Can't on mobile, but it's the top bar of this page: https://www.righttoknow.org.au/request/831/response/3195/attach/html/3/Document%201.pdf.html

**Comment by henare** [comment]
Duplicate of #354?

**Comment by benrfairless** [comment]
Correct! Thanks @henare
