### ISSUE TITLE
Simplify body list styles

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#415]
The list item dot points in the [body list (Authorities side bar)](https://www.righttoknow.org.au/body/list/all?post_redirect=1) are a very noisy way to make the separation between list items clear:

![screen shot 2015-03-04 at 4 23 38 pm](https://cloud.githubusercontent.com/assets/1239550/6478615/0220f612-c28b-11e4-99a3-de713eec99ef.png)

We could move to the default styles in the Alavateli responsive styles, which removes the points and increases the spacing between items to visually separate them. Maybe we could take that separation a little further? Here's the default example in [WhatDoTheyKnow](https://www.whatdotheyknow.com/body/list/all)

![screen shot 2015-03-04 at 4 23 33 pm](https://cloud.githubusercontent.com/assets/1239550/6478623/2b7766e0-c28b-11e4-824a-4a47468da608.png)

We could also loose the extra space on the left, as they have. This would also mean more of the authority names would fit on a single line.

**Comment by benrfairless** [comment]
I agree that dot points appear dated, and I prefer the WDTK version (but that's the opinion of someone who isn't a designer!)
