### ISSUE TITLE
Introduce better Analytics

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#416]
Google does an alright job of analysing what happens across the whole site, however I'm finding it difficult to get the below information from our current analytics:
- Who is creating accounts and:
  - Using their account only for annotations
  - Using their account to track things
  - Not using their account at all
  - Using (or not using) specific parts of the site (such as the categorisation game, profile page, help  pages)

When we can identify the "who" points above, I would like to try reaching out to those people to find out:
- What is the site doing well, and what does it need to improve on?
- What we can do to help people to use the site?
- How we can make the site better

I was looking at integrating Intercom into the site, which on the face of it would help with the above.

**Comment by henare** [comment]
I think this should be split out into upstream issues.
