### ISSUE TITLE
review wording on RTK for Federal and ACT 

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#417]
A heap of work has already been done on this - @henare asked me to review the site.

**Comment by kat** [comment]
http://test.righttoknow.org.au/help/requesting 

Who can make a request?  says 
"

```
Any person, of any nationality, anywhere in the world, however young or old can make a request under Federal Australian Freedom of Information (FOI) law.

The Freedom of Information Act simply says that "every person has a legally enforceable right to obtain access in accordance with this Act". A "person" can also be a body corporate, such as a company.
```

"
replace Freedom of Information Act, with Freedom of Information Acts 
replace Federal Freedom of Information (FOI) law. with Freedom of Information Laws.

**Comment by henare** [comment]
^^^ fixed in c1680a4

**Comment by kat** [comment]
nice work, we're done!

**Comment by henare** [comment]
:metal: :tada: :balloon:
