### ISSUE TITLE
request form is scrunched up, add space and simplify

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#425]
The layout of the request form is very tight vertically and appears somewhat randomly spaced horizontally. I think this would be more scannable and clearer with some vertical space between elements and if it was all bought into a consistent horizontal line. In particular it's not obvious why the 'possibly related requests' are indented—maybe there's a good reason?

![screen shot 2015-03-10 at 10 00 46 am](https://cloud.githubusercontent.com/assets/1239550/6566374/fb2b4520-c70c-11e4-8f23-0c1f5db353da.png)

**Comment by benrfairless** [comment]
I think Alaveteli are updating the way a request will be made going forward anyway (I think I read something, but can't recall) so I'm not sure if this is something we need to consider when looking into this.

On a slightly unrelated topic, I have always found the number of "possibly related requests" is usually far too long and has little meaning to what the person is tying into the summary box.

**Comment by henare** [comment]
> On a slightly unrelated topic, I have always found the number of "possibly related requests" is usually far too long and has little meaning to what the person is tying into the summary box.

Me too - I wonder why it's so long?

**Comment by benrfairless** [comment]
According to https://github.com/mysociety/alaveteli/blob/release/0.21/doc/CHANGES.md there have been some massive changes to the request function in 0.21. I suggest we hold fire on this to see if the upgrades to 0.21 fix some of the issues described here.

**Comment by equivalentideas** [comment]
I think this would be fixed by #523

**Comment by equivalentideas** [comment]
I think this is fixed by #534  :

![](https://cloud.githubusercontent.com/assets/1239550/7341730/9e423c8e-ecea-11e4-9c81-d2fe6fe566e3.png)
