### ISSUE TITLE
PDF appears blank in 'View as HTML'

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#426]
The document image in 'View as HTML' appears blank to me (it is quite pretty, but not what I was looking for):
![screen shot 2015-03-10 at 3 57 11 pm](https://cloud.githubusercontent.com/assets/1239550/6569449/80d3651e-c73e-11e4-89ed-a9e04ba22395.png)
See https://www.righttoknow.org.au/request/936/response/3262/attach/html/3/Signed%20response%2010.3.15.pdf.html

The [PDF version](https://www.righttoknow.org.au/request/936/response/3262/attach/3/Signed%20response%2010.3.15.pdf) looks like this:

![screen shot 2015-03-10 at 3 59 34 pm](https://cloud.githubusercontent.com/assets/1239550/6569459/97981330-c73e-11e4-8926-64ab626bca5e.png)

**Comment by henare** [comment]
#224 is a related kind of problem.
