### ISSUE TITLE
Modify law name used depending on jurisdiction of public body

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#428]
4 out of the 9 Australian jurisdictions use a name other than "Freedom of Information" for their information access law.

**Comment by henare** [comment]
From my investigation I think it will be a huge and painful job to change it throughout the application and completely impractical to dynamically change it based on the public authority's jurisdiction (because we couldn't even use translations for this - we'd have to override and change all the templates).

It would be really nice if upstream Alaveteli made the wording throughout the application generic, e.g. "make a new information request" vs. "make a new Freedom of Information request". With a really easy way to change that if you wanted to.

I think the most practical approach for us will be to consistently call it one thing in our application, but customise text that mentions the law in parts of the application that touch government, e.g. override the outbound email subject line to mention the appropriate law name.

**Comment by benrfairless** [comment]
RTK already does this for something called EIRs (which we don't use). If I could find a way to do something like what you [see here](https://github.com/openaustralia/alaveteli/blob/production/app/models/info_request.rb#L301) then it should be simple.

I was thinking of something in https://github.com/openaustralia/alaveteli/blob/production/app/models/public_body.rb like

``` ruby
#Defines qld_state as being everything that is tagged QLD_state
   def QLD_state?
        return self.has_tag?('QLD_state')
    end
```

If you then re-word the [info_request rb file](https://github.com/openaustralia/alaveteli/blob/production/app/models/info_request.rb#L301-L310) to reference the above defined state, you can re-word depending on where in the site:

``` ruby
    def law_used_full
        if self.public_body.qldstate?
            return _("Right to Information")
        elsif self.law_used == 'foi'
            return _("Freedom of Information")
        else
            raise "Unknown law used '" + self.law_used + "'"
        end
    end
```

I'm assuming I can make these changes in [model_patches.rb](https://github.com/openaustralia/righttoknow/blob/production/lib/model_patches.rb) but I'm not sure if the above would work?

**Comment by benrfairless** [comment]
I'm working on this here: https://github.com/openaustralia/righttoknow/tree/law-name
