### ISSUE TITLE
"Describe the status of this request" box has a different appearance

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#435]
Staging:

![selection_001](https://cloud.githubusercontent.com/assets/48945/6659035/65b684b0-cbcf-11e4-9907-7fcb0e58064b.png)

Production:

![selection_002](https://cloud.githubusercontent.com/assets/48945/6659038/75891254-cbcf-11e4-8942-03e04b8107c1.png)

**Comment by equivalentideas** [comment]
Fixed by commits https://github.com/openaustralia/righttoknow/compare/2c85ec6c5dbe...0fa0ac1e2e8e . Responsive styles now:
![screen shot 2015-03-16 at 2 50 51 pm](https://cloud.githubusercontent.com/assets/1239550/6660385/e1aa8e10-cbeb-11e4-9002-d361877ad6d3.png)
