### ISSUE TITLE
Text spacing slightly different

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#437]
Only on Chromium on Linux. Firefox on Linux is not affected.

![text](https://cloud.githubusercontent.com/assets/48945/6659098/5416ee8c-cbd1-11e4-91fe-88340ca91b47.gif)

**Comment by equivalentideas** [comment]
Tried to fix this with https://github.com/openaustralia/righttoknow/commit/ccee57e . There seems to be bugs in `text-rendering` see https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering#Browser_Compatibility . This could be a reason that the styles added in that commit were removed in the responsive styles.

I wont close this until I can see it fixed on staging.

**Comment by equivalentideas** [comment]
Fixed by https://github.com/openaustralia/righttoknow/commit/94bf47f8f1dfbc40f736981ebf34f0c5b107bd35 . The text-rendering actually had to be reset to browser default with 'auto'.
