### ISSUE TITLE
Authority update form different

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#440]
https://www.righttoknow.org.au/change_request/new?body=aaf_company

http://test.righttoknow.org.au/change_request/new?body=aaf_company

**Comment by equivalentideas** [comment]
I've matched these with https://github.com/openaustralia/righttoknow/compare/8f9b9ccc51...4b2ddf8bb5 all except for the textarea.

In the current theme the textarea has no styling and appears as the browser defined width, height and border style. Unfortunately the width of this default isn't flexible so it was overridden in the responsive styles. But now as far as I can see, it's not possible to reset it back to the browser default (which is different to 'auto') once it's set.

Here's the production Right To Know in Chrome:
![screen shot 2015-03-17 at 3 33 47 pm](https://cloud.githubusercontent.com/assets/1239550/6681721/c5f79f6c-ccbf-11e4-9a97-547772e7f622.png)

in Firefox:
![screen shot 2015-03-17 at 3 33 56 pm](https://cloud.githubusercontent.com/assets/1239550/6681722/cf89f4a8-ccbf-11e4-9a01-767a981279ac.png)

I don't see how we can have the textarea be both responsive, and also match the current design pixel for pixel. I can keep thinking, but it feels like a lot of effort for very little, and no gain for the citizen. @mlandauer have you got thoughts on this? Is this change acceptable?

**Comment by equivalentideas** [comment]
I think accepting this slight change to the width of the textarea on wide screens is an acceptable solution here.

I'm going to close this, and as always, if anyone has a better idea please reopen it :)
