### ISSUE TITLE
Sign in pages different

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#441]
I notice "- or -" has incorrectly wrapped too.

![sign_in](https://cloud.githubusercontent.com/assets/48945/6660686/bfbd312a-cbf2-11e4-95f6-29ec564b79e0.gif)

**Comment by equivalentideas** [comment]
made a few improvements to this with https://github.com/openaustralia/righttoknow/compare/53c9772a5716...9e833f84b311

Will come back around to this later, it's doing my head in a bit.

**Comment by equivalentideas** [comment]
fixed in https://github.com/openaustralia/righttoknow/compare/f0a292bde1b3...3f1644e42b0d
