### ISSUE TITLE
Tapping/Clicking the Anchor link on mobile takes you to the bottom of the page

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#444]
If you click an Anchor link on a request from a mobile device, you are whizzed down to the bottom of the page and have to scroll back up again.

**Comment by equivalentideas** [comment]
Thanks @brfairless can you chuck in a screenshot and url for the location you mean? Also what device are you using mate?

**Comment by benrfairless** [comment]
Happens on both iPhone and iPad, and I'm talking about the anchor button available on any request. I'll do one better then a picture :)

https://drive.google.com/a/openaustralia.org/file/d/0B6FvM3R1FeGaaGFveW80bThIMXc/view?usp=sharing

**Comment by equivalentideas** [comment]
This appears to be a bug upstream. I've recreated the it on whatdotheyknow.com as well, at https://www.whatdotheyknow.com/request/how_much_time_does_the_vice_chan .

I'm going to close this here, remove the milestone and report it upstream.
