### ISSUE TITLE
Error Messages aren't responsive

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#445]
If there are any errors when you create a request, the error box is not responsive:

iPhone 4S example:
![ios simulator screen shot 16 mar 2015 7 20 31 pm](https://cloud.githubusercontent.com/assets/6841582/6663865/454fd6e8-cc12-11e4-99a4-68bb81f16e0b.png)

**Comment by equivalentideas** [comment]
Thanks for that @brfairless :+1: I've fixed this with https://github.com/openaustralia/righttoknow/commit/8f9b9cc
