### ISSUE TITLE
Credits page spacing and text size differences

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#453]
Compare:

https://www.righttoknow.org.au/help/credits#supporting

http://test.righttoknow.org.au/help/credits#supporting

**Comment by equivalentideas** [comment]
Thanks for that @henare . I'll pick this up now.

**Comment by equivalentideas** [comment]
- [x] heading sizes are different
- [x] space at the bottom of list is different

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/righttoknow/compare/eda48d9cf168...61d2c617f74c

**Comment by henare** [comment]
@equivalentideas ^^^ these commit range references for multiple commits you've been doing lately has been really effective :+1:
