### ISSUE TITLE
Public authorities page has title after categories list

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#454]

**Comment by equivalentideas** [comment]
I'm not sure what you mean by this, could you add a link or screenshot?

**Comment by henare** [comment]
Visit http://test.righttoknow.org.au/body/list/all on your mobile. The categories are displayed first, before the title, so you don't even know what page you're on.

It's the same on the authority show page.

Here's my technologically advanced "screenshot"!

![2015-03-30-162039](https://cloud.githubusercontent.com/assets/48945/6890539/e0c62d3e-d6f8-11e4-80d9-6be1fb34f62a.jpg)

**Comment by equivalentideas** [comment]
That's beauty thanks!

**Comment by henare** [comment]
Same on the user profile page, e.g. http://test.righttoknow.org.au/user/henare_degan/

**Comment by equivalentideas** [comment]
I've logged this issue upstream https://github.com/mysociety/alaveteli/issues/2272 will close it here as discussed today.
