### ISSUE TITLE
Link on "Read blog" in staging doesn't match the one in production

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/righttoknow#455]

**Comment by equivalentideas** [comment]
@mlandauer Do you mean that the url in the link is different ? I think that's actually part of the config for staging and isn't part of this milestone.

**Comment by mlandauer** [comment]
Click on the link in the menu on both staging and production and you'll see that production takes you to the oaf blog directly. In staging it shows you another page on RTK. I'm pretty sure this difference is in the theme. It might just be a case of merging the latest stuff from the main branch across

**Comment by equivalentideas** [comment]
fixed in https://github.com/openaustralia/righttoknow/commit/674b9c88af05c7301f1229c9fe74991963bac296
