### ISSUE TITLE
Authority search doesn't find a certain authority

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#456]
I want to find the ACT Chief Minister so I go to _View authorities_ and type "act chief":

https://www.righttoknow.org.au/body/list/all?utf8=%E2%9C%93&public_body_query=act+chief&commit=Search

Which gives me one result that I don't want :( However searching using the search box in the top right does find it!

https://www.righttoknow.org.au/search/act%20chief/all

**Comment by benrfairless** [comment]
I've raised this upstream to try and push all search functionality via the search bits of alaveteli - https://github.com/mysociety/alaveteli/issues/2343
