### ISSUE TITLE
Possibly related requests on mobile when making a request is off to the side

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#457]
![screenshot 30 mar 2015 4_30_38 pm](https://cloud.githubusercontent.com/assets/48945/6890619/93977a0c-d6fa-11e4-9dcf-0032cf5e6c7d.png)

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/righttoknow/commit/597138240f5c5f1794ea99561cbdfc53ea32af1c
