### ISSUE TITLE
Flash message internal spacing a bit tight

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#458]
![screenshot 30 mar 2015 4_37_46 pm](https://cloud.githubusercontent.com/assets/48945/6890672/911fecc2-d6fb-11e4-9b39-da7016b2cca3.png)

**Comment by equivalentideas** [comment]
fixed in https://github.com/openaustralia/righttoknow/commit/cd31f540c214601acbb9326be43b055c5b924bfa
