### ISSUE TITLE
Annotation preview aligned oddly

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#459]
![screenshot 30 mar 2015 4_42_17 pm](https://cloud.githubusercontent.com/assets/48945/6890705/2d32974a-d6fc-11e4-99f2-c4494b0b83b7.png)

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/righttoknow/commit/72e86517f7141008382c51fa3dd1f5e9c4bfd8f7
