### ISSUE TITLE
Request status radio buttons warped

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#460]
Firefox on Android:

![screenshot 30 mar 2015 4_49_15 pm](https://cloud.githubusercontent.com/assets/48945/6890759/111eaf7a-d6fd-11e4-8400-545bde8dffc3.png)

**Comment by equivalentideas** [comment]
@henare I can't recreate this and can't find an emulator. Could you please confirm for me it's not an upstream issue?

**Comment by henare** [comment]
@equivalentideas doesn't happen on http://demo.alaveteli.org/

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/righttoknow/commit/076d172c33fc9fe98aa4674eaab45c82bca6f094
