### ISSUE TITLE
"Unhappy about your request?" page has no padding on mobile

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#461]
It makes things very squished on the left side:

![screenshot 30 mar 2015 4_50_23 pm](https://cloud.githubusercontent.com/assets/48945/6890770/42d8f8ae-d6fd-11e4-95a3-c07f50eb0ec3.png)

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/righttoknow/commit/6fc3131e02962709b8520411a9535c5bd1a8594a
