### ISSUE TITLE
Email content was not redacted

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#468]
The Mobile number and email address of an employee of NBNCo was not redacted:
https://www.righttoknow.org.au/request/information_regarding_rollout_in_2#incoming-3448

**Comment by benrfairless** [comment]
previously the email address has been, but not phone numbers in international format or email addresses (another example: https://www.righttoknow.org.au/request/nbn_rollout_regarding_plans_for#incoming-3185)

**Comment by benrfairless** [comment]
It turns out only emails are being redacted, not even UK based mobile numbers are redacted anymore! I've raised this upstream: https://github.com/mysociety/alaveteli/issues/2278

**Comment by henare** [comment]
Since this is opened upstream I'll close this issue.
