### ISSUE TITLE
Consider making fuller content available in RSS feeds

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/righttoknow#469]
![not_enough_context](https://cloud.githubusercontent.com/assets/365751/7003842/87c68280-dca0-11e4-896f-c0d3a5480062.png)

is what I get for https://www.righttoknow.org.au/request/call_scripts_ambulance#outgoing-2280

There's:
- No pre-formatting or line breaks as per the original email/input
- An emphasis on the status of the overall request which is somewhat unimportant for comments (useful for new requests or status changes I guess)
- The same kind of title as the original article/item - so you sometimes see 10x entries, one that might be important enough for you to click through and read the status; 9 which look the same. Hard to tell ham from spam.

**Comment by benrfairless** [comment]
I've just pulled a sample feed from another Alaveteli instance: https://www.whatdotheyknow.com/feed/request/council_tax_and_nndr_summons_and_12

I think the above improvements could be enjoyed by all upstream, so I'm going to raise the issue upstream. If I get time, I might work on the code and submit a PR upstream too!

**Comment by henare** [comment]
This is opened upstream so I'll close this. We'll deploy it if/when it gets accepted upstream.
