### ISSUE TITLE
'View as HTML' label is meaningless to the citizen

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#473]
For the link for citizens to view a document attached to a request in their browser:

![screen shot 2015-04-07 at 12 16 03 pm](https://cloud.githubusercontent.com/assets/1239550/7015983/1630e22a-dd20-11e4-87fc-5bceeee014db.png)

Why are we telling them what format it's in? Do they know what it means that it's in HTML?

Maybe a label like: 'View online' or 'View in your browser' or 'View text version' would be better?

On the document view page we also say "This is an HTML version of an attachment to the Freedom of Information request". Same question applies here.

**Comment by benrfairless** [comment]
@equivalentideas I'm wondering if it's even worth having that option. I agree the wording is poor, but that said I don't know of many people who use it (considering most documents are PDFs, and may not render properly).

If we choose to keep it, I agree that we should use a "View online" or "view in your browser" option.

**Comment by equivalentideas** [comment]
> I'm wondering if it's even worth having that option.

It would be interesting to see if there are any documented use cases, but here's an idea:
- As a user I need to view request documents without downloading them onto my device, which does not have this capability

I'm not quite sure what processing this does to the pdf text, but it may been making it more accessible to assistive technologies in the browser than the pdf would be otherwise. It might be more digestible to search engines as well, depending on the markup and meta tags etc.

It gives us the opportunity to add information about the document in the header, such as linking back to the request, to Right To Know, etc. I think that's quite important.

**Comment by henare** [comment]
I like where this is going but I think this should be raised upstream.

**Comment by equivalentideas** [comment]
> but I think this should be raised upstream.

I agree.

**Comment by equivalentideas** [comment]
Moved upstream https://github.com/mysociety/alaveteli/issues/2303

**Comment by henare** [comment]
Champion, thanks @equivalentideas.
