### ISSUE TITLE
Make 'View as HTML' page responsive

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#474]
I'm not sure why we aren't getting the responsive version of the 'View as HTML' page?

See What Do They Know for example of the responsive version: https://www.whatdotheyknow.com/request/261308/response/636793/attach/html/2/810078%20Berry.doc.html

I'm having trouble getting it to use the original partial in my dev version, even after removing our overriding `request/_view_html_prefix.html.erb` partial. The way the request controller works is pretty foreign to me but I think it's a caching thing? I wonder if @henare can have a squiz at this?

**Comment by equivalentideas** [comment]
Is there a possibility we could use an external doc view like the [Internet Archive's](https://archive.org/stream/NSW_Pecuniary_Interests_2013-2014/2014-06-30_Hancock_Shelley_pecuniary-interests#page/n3/mode/2up) or Google Docs, like [What Do They Know](https://www.whatdotheyknow.com/request/261308/response/636793/attach/html/2/810078%20Berry.doc.html)?

Related to https://github.com/openaustralia/righttoknow/issues/475

**Comment by henare** [comment]
> I think it's a caching thing?

Yes, I think you're right.

> I wonder if @henare can have a squiz at this?

Sure can.

**Comment by henare** [comment]
I've deleted the cache by removing these two directories:

```
/srv/www/www.righttoknow.org.au/shared/cache/attachments_production/
/srv/www/www.righttoknow.org.au/shared/cache/views/
```

This was long overdue as we fixed a bug a while ago and also changed the design recently and none of these changes were reflected in already-cached HTML views. So we need to remember to do this when we make changes to the HTML view stuff.
