### ISSUE TITLE
Response has gone outside the response text

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#476]
https://www.righttoknow.org.au/request/call_scripts_ambulance#incoming-3454

The response on the above has gone siginficantly over the side (seen in Chrome on Windows):
![capture](https://cloud.githubusercontent.com/assets/6841582/7016851/b3180c06-dd2c-11e4-8c3c-57e2ba434f21.PNG)

**Comment by equivalentideas** [comment]
@brfairless do you mean that there isn't margin between the text and the edge of the box?

I can't see this on my mac. Is this a problem across all the correspondence boxes?

**Comment by benrfairless** [comment]
I can't replicate this again. Maybe this was a disturbance in the force.
