### ISSUE TITLE
Spacing around avatar thumbnail in annotation a little ackward

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/righttoknow#479]
See https://www.righttoknow.org.au/request/prime_minister_gift_of_tie_and_b#comment-948

![prime minister gift of tie and bike to museum a freedom of information request to museum of australian democracy right to know](https://cloud.githubusercontent.com/assets/2221/7041974/7845f746-de21-11e4-8303-b44a0ff4339f.png)

**Comment by henare** [comment]
Similar to #223.

**Comment by equivalentideas** [comment]
This is an upstream issue. The problem stems from the 'padding' on the correspondence boxes being implemented with margin on the elements inside, which is uneven. I'm going to have a quick go at improving the implementation upstream so this is _way_ simpler and then patching it on our end.

**Comment by equivalentideas** [comment]
This will get fixed https://github.com/equivalentideas/alaveteli/commit/807bcc5f2e415243832e0f8b03f1ac1d36b9c522 get's merged into alaveteli and we update. I'll do a quick patch in our theme that can hold till then.
