### ISSUE TITLE
Work out what to do with ACT schools

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#482]
@brfairless discovered on #463 that in the ACT individual schools aren't really FOIable - the request would be referred to the Directorate.

We've already added them to RTK so now we have to decide whether to:
- Delete them - What about people searching the site or Google?
- Mark them as not FOIable with a note telling people to FOI the appropriate directorate - this means we'll have heaps of authorities that aren't really FOIable which clutters the site and increases the maintenance burden

**Comment by benrfairless** [comment]
The maintenance burden makes me lean towards getting rid of them

**Comment by henare** [comment]
It also feels wrong to add a whole bunch of authorities that aren't actually authorities for FOI purposes. It will be confusing because you wouldn't expect it. It's different to our choice to include excluded agencies because you can effectively FOI schools via their department, i.e. schools are effectively sub-units of the department in our case.

So I agree, let's delete them. We still need to complete the research of #463 and I'm keen to get that done soon so we fully understand this issue.

**Comment by benrfairless** [comment]
I'm deleting all the schools now!

**Comment by henare** [comment]
Ain't no :school: like the deleted :school:

**Comment by benrfairless** [comment]
So I've marked them all as `not_apply` so people can't make requests to them while I go through and destroy them all!

:hammer: the :school:

**Comment by henare** [comment]
33 left to delete so I'll do that now.

**Comment by henare** [comment]
Done.

**Comment by henare** [comment]
We missed colleges: https://www.righttoknow.org.au/body/list/college

**Comment by benrfairless** [comment]
All gone now

**Comment by henare** [comment]
Thanks Ben!
