### ISSUE TITLE
Select an authority page layout different

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#487]
The layout of this page has changed in 0.20:

![selection_001](https://cloud.githubusercontent.com/assets/48945/7104350/451db300-e11d-11e4-9c96-aca91984808b.png)

WDTK for comparison:

![selection_002](https://cloud.githubusercontent.com/assets/48945/7104351/4d31c446-e11d-11e4-861c-d7b50d7e9778.png)

**Comment by henare** [comment]
Non-responsive looks OK:

![selection_001](https://cloud.githubusercontent.com/assets/48945/7104407/8a4f68ba-e122-11e4-9e07-6a2f6e2b50d1.png)

**Comment by henare** [comment]
Can you please take a look at this @equivalentideas?

To reproduce checkout the `staging` branch from our Alaveteli fork and add changes to the `v0.20` branch of our theme which will be added to #489.

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/righttoknow/commit/411f5b33d8a601897e77146aabb42a4d2c63d726

**Comment by equivalentideas** [comment]
Just a note that your screenshot of WDTK is actually at version .21 , I'm made this match the layout at [.20](https://github.com/mysociety/alaveteli/blob/823e58dc69960c600230b10604a0051359173f85/app/assets/stylesheets/responsive/_new_request_layout.scss) .

![screen shot 2015-04-13 at 11 11 04 am](https://cloud.githubusercontent.com/assets/1239550/7108560/d14fbffc-e1cd-11e4-974f-4292e9b5881f.png)
