### ISSUE TITLE
"Preview your request" button not aligned

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#490]
It's not left aligned with the rest of the content, is this a bug?

![selection_001](https://cloud.githubusercontent.com/assets/48945/7104500/39ed91c4-e129-11e4-8639-a355399ab740.png)

**Comment by equivalentideas** [comment]
>  is this a bug?

No, it's actually part of the current design. Presumably it's meant to make the buttons more eye-catching by breaking the horizontal line of the layout. I don't think it's necessary, and that it makes the page appear dis-ordered. Without usability testing to confirm, I'd say that the distinct button style is attention grabbing enough.

**Comment by henare** [comment]
Thanks @equivalentideas. I'm happy to close this then.
