### ISSUE TITLE
If a request is successful we shouldn't request status updates on future emails

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#491]
https://www.righttoknow.org.au/request/correspondence_referencings_usag#incoming-3487

There has been some back and forth chat, but the request was already marked as successful so we shouldn't be asking people to re-clarify new responses.

**Comment by henare** [comment]
Probably a good idea but definitely one for :point_up: upstream

**Comment by benrfairless** [comment]
https://github.com/mysociety/alaveteli/issues/2342
