### ISSUE TITLE
remove captcha from sign up form

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#492]
In staging there is a captcha form on the sign up form http://test.righttoknow.org.au/profile/sign_in . Unless we have a spam problem and can't think of another fix, I think we should remove it as captchas are a nasty users experience in my opinion.

**Comment by benrfairless** [comment]
There isn't a problem on staging, but we do have an issue with Spam Accounts in production.

 I would like us to use the new "NOCAPTCHA" if possible, but I think it needs an update to a gem in alaveteli and I don't know how to do that!

## 

Ben Fairless
Right to Know Volunteer

e: ben@rightotknow.org.au
w: www.rightotknow.org.au
t: @RighttoKnowAu

**Comment by henare** [comment]
I cannot reproduce, can you please check this @equivalentideas?

**Comment by henare** [comment]
Worked out that Alaveteli shows the CAPTCHA if it detects you're from a foreign country.

@equivalentideas was seeing this because he's using a VPN.
