### ISSUE TITLE
Edit your request button is a half-button, half-link mutant!

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#501]
![selection_001](https://cloud.githubusercontent.com/assets/48945/7111958/7be8c050-e208-11e4-9e37-8b5b935448ae.png)

**Comment by henare** [comment]
WDTK has it as a link:

![selection_003](https://cloud.githubusercontent.com/assets/48945/7111990/8f3598c2-e208-11e4-9cf4-7d10240fdfce.png)

**Comment by benrfairless** [comment]
I think we should change it to a link, this emphasises the sending of the request and will help guide people through the process (In my opinion)

**Comment by henare** [comment]
SGTM.
