### ISSUE TITLE
use alaveteli grid system by removing overrides

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#503]
In our current [custom.scss](https://github.com/openaustralia/righttoknow/blob/production/assets/stylesheets/responsive/custom.scss#L391) there are lots of places where we override the default widths and layout of Alaveteli. These were mostly added to match our widescreen responsive styles to the non-responsive version of our theme when we [upgraded to the responsive version](https://github.com/openaustralia/righttoknow/pull/452).

If we remove these overrides we'll simplify our theme and make it more maintainable with upstream. Many of their changes also make the layout more consistent.

**Comment by benrfairless** [comment]
I like this idea, we shouldn't be doing more then required in this repo

**Comment by equivalentideas** [comment]
Steps to this:
- [x] remove override of site max-width. This will make all our pages about 10% wider
- [x] remove hardcoded column widths
- [x] remove hardcoded frontpage widths

**Comment by equivalentideas** [comment]
There's something a bit more complex going on with the describe_state_form layout that needs another look.

**Comment by equivalentideas** [comment]
There are quite a few grid overrides relating to our horizontal form label-input design.

Those should be dealt with in #523 .
