### ISSUE TITLE
Make it easy for admins to find authorities with no jurisdiction tag

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#505]
Our customised theme uses tags to determine what jurisdiction an authority is in. If a public body doesn't have a tag indicating its jurisdiction we just default to Alaveteli's configuration (which is set to the same as Federal on Right To Know).

However since missing a tag is an easy mistake (there are 12 that are missing a jurisdiction tag as I type) it seems like a good check to add to our admin pages.

In the mean time this search can find authorities without a jurisdiction tag:

https://www.righttoknow.org.au/search/variety:authority%20NOT%20tag:federal%20NOT%20tag:ACT%20NOT%20tag:NSW%20NOT%20tag:NT%20NOT%20tag:QLD%20NOT%20tag:SA%20NOT%20tag:TAS%20NOT%20tag:VIC%20NOT%20tag:WA%20NOT%20tag:ACT_state/all?commit=Search&utf8=%E2%9C%93

**Comment by benrfairless** [comment]
Could we use a Morph scraper to scrape each authority, and report those which don't have a category?

**Comment by henare** [comment]
It would be pretty cool if we could add another model patch to our theme that adds a validation checking for the presence of a jurisdiction tag when adding/editing an authority.

**Comment by henare** [comment]
> there are 12 that are missing a jurisdiction tag as I type

I've added the `federal` tag to these.

**Comment by henare** [comment]
That search works pretty well so I'll close this.

**Comment by henare** [comment]
I used the search above to find another couple:

* https://www.righttoknow.org.au/body/royal_australian_and_new_zealand_college_of_obstetricians_and_gynaecologists was added (by me I think) at the request of someone. It's easy to miss tagging authorities added when someone requests adding them because adding tags isn't in the flow
* https://www.righttoknow.org.au/body/nsw_valuer_general was added by @benrfairless. It had the `NSW_state` tag but not the `NSW` tag. You need both because one drives the categorisation and one configures the FOI law parameters
