### ISSUE TITLE
Add Public Holidays

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#512]
We need to add the National Public Holidays, and consider adding ACT ones as well using the new interface.

When that's done, we need to set `WORKING_OR_CALENDAR_DAYS` to `working` in general.yml

**Comment by henare** [comment]
> We need to add the National Public Holidays, and consider adding ACT ones as well using the new interface.

SGTM - we should just add all holidays for all states as a matter of course from now on.

> When that's done, we need to set WORKING_OR_CALENDAR_DAYS to working in general.yml

We don't need to make any changes - our theme [magically sorts that out](https://github.com/openaustralia/righttoknow/blob/production/lib/model_patches.rb#L46-L53) based on the jurisdiction now.

**Comment by benrfairless** [comment]
> we should just add all holidays for all states as a matter of course from now on.

In that case, I propose we import the [Google iCal Feed](https://www.google.com/calendar/ical/en.australian%23holiday%40group.v.calendar.google.com/public/basic.ics) into RTK. Are there any objections with this approach?

The only downside I see is that the due dates will be wrong if one state doesn't observe a specific public holiday, however that will give the authority more time, not less to respond to a request.

**Comment by henare** [comment]
> In that case, I propose we import the Google iCal Feed into RTK. Are there any objections with this approach?

Just be careful of which ones you import. I tested that feed and it includes "holidays" for when daylight savings time starts and ends and a few other ones we don't want.

Also be careful of this bug: https://github.com/mysociety/alaveteli/issues/2347

> The only downside I see is that the due dates will be wrong if one state doesn't observe a specific public holiday, however that will give the authority more time, not less to respond to a request.

I'm fine with this. As we say [on the site](https://www.righttoknow.org.au/help/officers#days), "...we try to be as generous as possible in our calculation of the timeframe."

**Comment by henare** [comment]
I've added the holidays from that feed for 2015, removing just the most obvious wrong ones.

**Comment by equivalentideas** [comment]
Re-opening this as we just got this message from Right To Know:

> It’s the time of year when your site needs to have next year’s public
> holiday dates added to it. (It may seem a bit early but the site needs
> to know about holidays at least 20 days before the first one takes place
> for it to calculate when responses are due properly, and you may need to
> set aside some time to work on this.)
> 
> There’s a tool for doing this in the admin interface.
> The instructions are here:
> 
> ```
> http://alaveteli.org/docs/installing/next_steps/#add-some-public-holidays
> ```
> 
> Depending on how your site is set up, you should get be able to import the
> holiday dates with the autosuggest feature. If this doesn’t look right,
> you’ll need to add the dates individually using the ‘New holiday’ button for
> each one. Don’t worry about weekends - it won’t hurt the site if you do add
> them, it will just take up more of your time! - as the site will work that
> out for you, it’s just national holidays that it needs to be told about.

**Comment by benrfairless** [comment]
I can do this tonight if you want?

## 

Ben Fairless
Volunteer - Right to Know - @RightToKnowAu

A project of the OpenAustralia Foundation

**Comment by benrfairless** [comment]
I've added 2017 holidays using this iCal: https://www.google.com/calendar/ical/en.australian%23holiday%40group.v.calendar.google.com/public/basic.ics
