### ISSUE TITLE
Admins can't download Email Attachments

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#513]
I'm unable to download the email attachments for this message: https://www.righttoknow.org.au/admin/raw_emails/3499

When I click the download button, I'm placed into a Login Loop. Can someone else test this and confirm if this is a problem for them?

**Comment by benrfairless** [comment]
Seems like it's affecting all the ones I've tried...

**Comment by henare** [comment]
Happens for me too.

I've tested in development and staging and it works OK.

**Comment by henare** [comment]
The issue was with Varnish. I've fixed our configuration and opened https://github.com/mysociety/alaveteli/pull/2338 upsteam.
