### ISSUE TITLE
Sharing requests via Twitter only provides the subject and a link

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#516]
When you share a request via twitter, it only provides the subject of the request, a link to the request, and our twitter handle:
https://twitter.com/benrfairless/status/589730438203060224

Suggest we provide a bit more wording, such as:

> I just made an #FOI request (`REQUEST_NAME`) online. `REQUEST_LINK` via `RTK Twitter Handle`

**Comment by henare** [comment]
Should be raised upstream.
