### ISSUE TITLE
move to vertical form design

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#523]
In our theme we override the default form design of labels stacked on top of form inputs:

[Right To Know](https://www.righttoknow.org.au/new/sydney_catchment_authority):
![screen shot 2015-04-24 at 9 46 29 am](https://cloud.githubusercontent.com/assets/1239550/7309837/de042cdc-ea66-11e4-9b1f-d8b7c7b8251b.png)

[Alaveteli Demo](http://demo.alaveteli.org/new/dfh):
![screen shot 2015-04-24 at 9 44 08 am](https://cloud.githubusercontent.com/assets/1239550/7309863/3b5298ec-ea67-11e4-819d-f38fc8a74c32.png)

I don't think this helps the user in any clear way and makes our theme more complex.

Scanning the labels vertically breaks up the flow of the page and distracts from the immediate task at hand: writing a summary of your request.

**Comment by equivalentideas** [comment]
@henare do you have any thoughts on this?

**Comment by henare** [comment]
I don't know what's best usability-wise. I'd lean slightly towards inheriting upstream but that's for technical reasons, i.e. we don't have to maintain the customisation.
