### ISSUE TITLE
Blog post announcing addition of NT and NSW authorities

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#540]

**Comment by henare** [comment]
A really helpful suggestion at AlaveteliCon was that when you're first engaging with a set of authorities you should start by pointing out good behaviour as examples for other authorities to follow rather than focussing on bad behaviour.

IIRC it comes from the idea that most authorities want to help but just don't know how to do it properly and only a small set are deliberately trying to frustrate the process.

So instead of waiting to work things out with NSW and NT, I think we should go ahead with this blog post pretty quickly and point out the couple of helpful responses we've got so far. We should also talk about application fees and our hope that most requests don't need to be subject to that process.

A big advantage of going ahead with this pretty quickly is that it removes the blocker for us adding other authorities.

**Comment by mlandauer** [comment]
I like! Do it!

**Comment by henare** [comment]
Overnight I've been thinking how to position this. Mainly in light of some more thinking from #Alaveteli15.

It's about how to promote your site and it's written up in [this blog post](https://www.mysociety.org/2015/06/02/ten-ways-to-promote-alaveteli-sites/) under "Make FOI concrete". It's something we think a lot about but it's worth repeating.

> Freedom of Information can be rather an abstract concept to the average person, so your tweets, blog posts and press releases might not be getting through to them.
> 
> Instead of asking people ‘what would you ask under the FOI act?’ or ‘Isn’t freedom of information a valuable right?’, try asking more concrete questions like ‘what would you like to know about government spending?’ or ‘if you could ask one question about nuclear defence, what would it be?’

However these announcement blog posts never get a huge amount of traction, Analytics says the ACT one had 41 unique views, so I don't think they're for potential requesters. My guess would be those 41 views are FOI or transparency nerds.

Since this post should address the problem of application fees we should also write it as a thing to point people to so they can understand where we're going with supporting jurisdictions with broken laws. So I think the audience is our usual FOI geeks and also FOI officers potentially.

**Comment by henare** [comment]
We've got a post ready to publish tomorrow around 10.

**Comment by henare** [comment]
:newspaper:  https://www.openaustraliafoundation.org.au/2015/06/11/a-step-forward-for-open-government-in-nsw-and-the-nt/
