### ISSUE TITLE
The PDF on this email appears to be broken

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#545]
https://www.righttoknow.org.au/request/k5_release_date#incoming-4427

Downloading the PDF looks like this:
<img width="512" alt="pdf error" src="https://cloud.githubusercontent.com/assets/6841582/11929795/039bfe14-a819-11e5-8244-7e0bdd55c204.png">

But viewing it in HTML works fine: https://www.righttoknow.org.au/request/1422/response/4427/attach/html/2/LEX%204659%20FOI%20Hamming%20K5%20RHDV%20virus%20Notice%20of%20decision%20on%20access%20original%20decision.pdf.html

**Comment by equivalentideas** [comment]
A couple more examples of this bug in the decision letters for these requests:
- https://www.righttoknow.org.au/request/k5_release_date#incoming-4427
- https://www.righttoknow.org.au/request/social_media_policy_8#incoming-5504

All our current examples are decision letters. I wonder if that means anything?

**Comment by henare** [comment]
Those all seem to be working now.
