### ISSUE TITLE
Character entities show in title when trying to follow a request

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#547]
Reported here: https://twitter.com/grumpymojo/status/689968032844779520

e.g. https://www.righttoknow.org.au/track/request/australia_posts_standard_postcod

Looks OK on the UK site, maybe we just need to update Alaveteli? https://www.whatdotheyknow.com/track/request/robocall_and_telemarketer_blockl

**Comment by equivalentideas** [comment]
This appears to be fixed:

Here's the report:
![czncrolwwaavtmr](https://cloud.githubusercontent.com/assets/1239550/17514579/b7e32bea-5e76-11e6-8fdc-7e7abb567236.jpg)

Here's now:
![screen shot 2016-08-09 at 9 17 33 pm](https://cloud.githubusercontent.com/assets/1239550/17514584/bf6e8102-5e76-11e6-864c-c28c829cb7b5.png)
