### ISSUE TITLE
not seeing all analytics - landing page not tagged properly?

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#548]
Just saw the following error in Analyics:

Clicks and Sessions Discrepancy
The AdWords ad destination URL www.righttoknow.org.au/ has significantly more AdWords clicks than Analytics sessions, most likely because the ad landing page is not properly tagged with Google Analytics.

**Comment by kat** [comment]
checking into this is seems the wrong Google Analytics tracking code is on a couple of pages - here's one report - login to analytics to see the other one. 'just' need to update the code to see how it's really performing. @henare @equivalentideas either of you interested in this one? Incentive? Our reported clicks will go up, they're not all being tracked now.

![screen shot 2016-02-24 at 11 08 50 pm](https://cloud.githubusercontent.com/assets/95376/13285018/42ec3d48-db4c-11e5-8ee7-147869c2c225.png)

**Comment by henare** [comment]
@kat it's now showing me this:

![selection_004](https://cloud.githubusercontent.com/assets/48945/13419412/162e7fc0-dfd2-11e5-967f-ac8810836cb1.png)

It's saying stuff about latency so it could be because Right To Know is s l o w.

**Comment by mlandauer** [comment]
I'm going to assume this is fixed or will be fixed by doing upgrades
