### ISSUE TITLE
show gratitude to community members when they help a requester

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#559]
Currently site admins send personal messages of thanks when they're alerted to helpful activity by someone in the RTK community. We could make a point of thanking through the system and more often.

**Comment by henare** [comment]
When someone reports a request we manually thank them. There are many circumstances when this information shouldn't be public so we probably don't want this automated.

When someone adds an annotation Alaveteli already thanks them. If someone requests we add or change an authority they're emailed a thanks by Alaveteli.

Are we already doing this? Let's reopen it if we can think of other ways when we might want to do this.
