### ISSUE TITLE
International Right to Know day event

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#567]
on international Right to Know day:
- International FOI muster (around a problem of global proportions) - eg Climate Change
- Maybe related to above... Get people in different countries to make requests from other countries (That idea from Danny OBrien years ago on one of their retreats).
- FOI Awards - include FOI mentor award, celebrate agencies that have worked well or made big improvements in how they handle FOI requests or have been responsive to requests for information (for example by taking cues from FOI requests and used that to proactively release related information that's valued by the public).
- FOI showcase/mentoring / Google Hangout with successful requesters
- Share successful FOI stories including how the information was put to use to make positive improvement in people's lives.

**Comment by henare** [comment]
We dedicated our [pub meet](https://www.meetup.com/OpenAustralia-Foundation/events/230629186/) to RTK day and we had an open day at Frontyard. And launched [total coverage](https://www.openaustraliafoundation.org.au/2016/09/28/happy-right-to-know-day-you-have-the-right-to-know-now-right-across-australia/) for RTK.
