### ISSUE TITLE
have high profile people to make requests on issues they care about

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#570]
During our conversation someone suggested that people don't care about FOI and that they follow celebrities. My flippant retort of a suggestion in response is: so get celebrities to make FOI requests! 

An example might be Ellen Degeneres who's been campaigning to save the great barrier reef. So an organisation campaigning to save the reef.  if she put in an FOI request around how decisions were taken to allow various commercial activities that affects the health of the reef, this would be a newsworthy thread, for example. The example thrown in the ring originally was Kim Kardashian, but I have no idea what this person might request. Related to #564

**Comment by mlandauer** [comment]
I think I'll close this as a "very unlikely but intriguing idea"
