### ISSUE TITLE
Other country message poorly displayed in our theme

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#578]
![selection_001](https://cloud.githubusercontent.com/assets/48945/17204427/d0a20d1e-54e8-11e6-87ad-21ef75a0f522.png)
- [x] the link text is unreadable
- [x] there is extra space above the notice

**Comment by equivalentideas** [comment]
Fixed in https://github.com/openaustralia/righttoknow/compare/239bc63ffb31...d8e8676be69c

![screen shot 2016-08-08 at 8 20 22 am](https://cloud.githubusercontent.com/assets/1239550/17465647/212c5d6a-5d41-11e6-8c32-2859bbcf3633.png)
