### ISSUE TITLE
Create higher resolution version of logo

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#579]
Alaveteli 0.23 introduces a highdpi version of the logo. They say:

> Should be at least 2x the size, in the same proportions

**Comment by henare** [comment]
I've tried to find a vector version of our logo to do this but it isn't in this repo and it wasn't attached to [the issue](https://github.com/openaustralia/righttoknow/issues/22).

@kat can you please have a look and see if you can find a copy? It would be also awesome if you could create the higher resolution raster for me to put up too.

**Comment by henare** [comment]
So I can proceed with the upgrade I might just set it to the same file for the moment. I'm guessing that's what's already happening for these users so it won't be a regression.

**Comment by equivalentideas** [comment]
@kat if you know where the vector version of the logo is lying around it would be awesome if you could chuck it on here. I'm looking for it to put on a slide for the workshop next week.

**Comment by p0sty** [comment]
Did you find the vector version? :)

**Comment by jamezpolley** [comment]
I've now assigned all the Kats

**Comment by katska** [comment]
Unfortunately that's not available. I didn't file it anywhere sensible. Sorry. @jamezpolley please can you attach the image that you want to recreate as a vector file?

**Comment by mlandauer** [comment]
I found the original adobe illustrator file we were sent. Looks like I can't attach it to the issue because github doesn't support it. Here's a link to it on google drive: https://drive.google.com/file/d/15Xzj7tMODyh-tbkkLWvz_9uJXcVqMo1v/view?usp=sharing

**Comment by benrfairless** [comment]
This is for the old logo on RTK, so I'm closing this issue.
