### ISSUE TITLE
Admins cannot use remember me when signing in

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#582]
If I check "remember me" when I sign in it appears I've signed in OK but then when I click something else I'm signed out. Steps to reproduce:
- Go to sign in page: https://www.righttoknow.org.au/profile/sign_in
- Sign in and check "remember me"
- You'll be shown a page where you're signed in
- Click a link (any link) and on the subsequent page you're signed out

This happens in production and staging. It doesn't happen locally in development.

**Comment by henare** [comment]
If you try to use remember me when signing in [as an admin](https://www.righttoknow.org.au/admin/) it just won't log you in - you're sent straight back to the same sign in page.

**Comment by henare** [comment]
I've tested this with a non-admin account and they don't seem to be affected.

**Comment by henare** [comment]
@equivalentideas can you please see if you can reproduce this with your account?

**Comment by equivalentideas** [comment]
I can't reproduce this following those steps @henare .
- I can log in with 'remember me' selected and navigate the site and remain logged in.
- I can log in as admin with 'remember me' selected

I'll assign this back to you.

**Comment by henare** [comment]
I can't reproduce in Chrome, only in Firefox. @equivalentideas can you please try once more in Firefox?

**Comment by equivalentideas** [comment]
Works for me in Firefox too.

**Comment by henare** [comment]
Thanks for checking!

On Friday, 5 August 2016, Luke Bacon notifications@github.com wrote:

> Works for me in Firefox too.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci3.googleusercontent.com/proxy/vDlEduJYFbvVnMuMi4NcIC099j_39q7RtiqFd86xRM6tgR3xxv26gcP_082xYG70mvIKY10_Qa7jBGwEhZutBn4F48XPX6Z1Mm4-6MRqf4hR-aYrHDv6_FfKHmkRSGkG_xRtaqXbhm1GR8l-0YU7k8ZfBSdzeg=s0-d-e1-ft#https://github.com/notifications/beacon/AAC_MX_G96FYJ9r6At4P6wo1iFxB3B3Wks5qctlqgaJpZM4JbQsS.gif

## 

## 

Henare Degan
OpenAustralia Foundation https://www.openaustraliafoundation.org.au/ -
@OpenAustralia https://twitter.com/OpenAustralia

**Comment by henare** [comment]
Well thanks to @equivalentideas' testing I think this is just my browser so I'll close this. Stupid browser.
