### ISSUE TITLE
Cannot deploy without special configuration after Ruby changes

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#591]
After our Ruby upgrade @equivalentideas can't deploy. After much fiddling it turns out that one of the hacks I tried when I was investigating ways to do the upgrade was still in place on my machine. So instead of our current setup working it was just a convenient alignment of hacks :full_moon_with_face: 

I have this in my `~/.caprc` file (the [hardcore method](https://rvm.io/deployment/capistrano#environment)):

``` ruby
set :default_environment, {
  'PATH' => "/home/alaveteli/.rvm/gems/ruby-2.0.0-p648/bin:/home/alaveteli/.rvm/gems/ruby-2.0.0-p648@global/bin:/home/alaveteli/.rvm/rubies/ruby-2.0.0-p648/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/alaveteli/.rvm/bin:/home/alaveteli/.rvm/bin",
  'RUBY_VERSION' => 'ruby-2.0.0-p648',
  'GEM_HOME'     => '/home/alaveteli/.rvm/gems/ruby-2.0.0-p648',
  'GEM_PATH'     => '/home/alaveteli/.rvm/gems/ruby-2.0.0-p648:/home/alaveteli/.rvm/gems/ruby-2.0.0-p648@global'
}
```

I guess we could put that in our version of Alaveteli but that feels like wrong hardcoding and also I've been very reluctant to let our Alaveteli diverge from upstream.

Since rbenv is supported by Alaveteli maybe we should use that instead?

**Comment by henare** [comment]
I think I've got it working _without_ having to do the really painful switch from RVM to rbenv.

What I did was look at how Alaveteli calls rbenv and I've tricked it into doing the same but for RVM. This will probably trip us up down the track but, crazily enough, it does seem like the best situation for now.

So what I did was symlink `/home/alaveteli/.rbenv/shims/` to RVM's wrappers:

```
ln -s /home/alaveteli/.rvm/wrappers/ruby-2.0.0-p648 .rbenv/shims
```

And then put a `rbenv-version` file into the shared files:

```
echo "2.0.0-p648" > /srv/www/test.righttoknow.org.au/shared/rbenv-version
```

This means that Alaveteli thinks that [rbenv is configured](https://github.com/openaustralia/alaveteli/blob/16c71ea7f300e45133f0f05387924a5eb00df7a5/config/deploy.rb#L22-L26) and [adds the `.rbenv/shims` directory to the path](https://github.com/openaustralia/alaveteli/blob/16c71ea7f300e45133f0f05387924a5eb00df7a5/config/deploy.rb#L28-L34) (which is actually symlinked to RVM).

So many hacks.

I've removed my `~/.caprc` and deployed both staging and production and confirmed they worked and with Ruby 2 from what I can tell.

@equivalentideas can you please see if you can deploy now?

**Comment by equivalentideas** [comment]
> @equivalentideas can you please see if you can deploy now?

I can! I just successfully deployed to staging. Closing this.

**Comment by henare** [comment]
:tropical_drink: :tada: Finally! :tropical_drink: :tada: 

:satisfied:
