### ISSUE TITLE
Recaptcha on sign up page not configured correctly

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#594]
You see this when you're signing up from overseas:

![selection_001](https://cloud.githubusercontent.com/assets/48945/17653652/24b5bb70-62dc-11e6-8cc4-e8132eae08a0.png)

**Comment by garethrees** [comment]
Just noticed this myself. I expect you're on it, but you just need to fill in https://www.google.com/recaptcha/admin#list and add the tokens to `general.yml`.

**Comment by henare** [comment]
Super, thanks @garethrees - that made fixing it really easy.

I must have missed this change in the release notes, oops :smile:
