### ISSUE TITLE
When I'm deciding which authority I should request from, make suggestions as I type, so I find the right one more quickly

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#595]
Since people are trying to find a specific authority by name, we can help them do this more quickly by suggesting authorities as they type.

![screen shot 2016-08-15 at 3 23 12 pm](https://cloud.githubusercontent.com/assets/1239550/17656328/33da74ae-62fc-11e6-9b40-ddbe2d2004ea.png)

This could be done with a simple dataset attribute for starters like on They Vote For You:

![screen shot 2016-08-15 at 3 22 17 pm](https://cloud.githubusercontent.com/assets/1239550/17656321/14570908-62fc-11e6-8dff-c245d896fbce.png)

**Comment by henare** [comment]
@equivalentideas it already does:

![selection_002](https://cloud.githubusercontent.com/assets/48945/17656469/ce9fae04-62fd-11e6-9234-4df4a7a86ff1.png)

So it sounds like you encountered a bug. Can you please try to reliably reproduce it and debug it?

**Comment by equivalentideas** [comment]
Nice, looking again, I do get this, but it's extremely slow and confusing. I'll see if I can work out why.

**Comment by equivalentideas** [comment]
So the problem is that it's just really slow. It's the same on whatdotheyknow.com so I'm going to raise this upstream.
