### ISSUE TITLE
Highlighting of search term is inconsistent

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#600]
When you use search in different places, the highlighting of the search term in the results in inconsistent.

Compare:
- https://www.righttoknow.org.au/search/Health/all
- https://www.righttoknow.org.au/select_authority?utf8=%E2%9C%93&query=Health&bodies=1&commit=Search
- https://www.righttoknow.org.au/user/james_smith_3?utf8=%E2%9C%93&user_query=Health&request_latest_status=&commit=Search+contributions+by+this+person

It's generally helpful, so unless there is some good reason to change it between sections it should be consistent.

**Comment by mlandauer** [comment]
I'm going to close this as a problem that will likely be resolved by upgrading Alaveteli and updating the theme
