### ISSUE TITLE
share admin functions with users to share ownership and practise openness by default.

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#602]
What things do we have access to see as admin that the user doesn't see? How much of that can we share?

**Comment by equivalentideas** [comment]
@kat Do you think it would be helpful here to explain why we would do this, or why it's helpful to people? I always find the 'why' extremely helpful when picking up issues.

**Comment by henare** [comment]
> I always find the 'why' extremely helpful when picking up issues.

:+1: it's probably a good idea to go back and do that to all the ones we've recently added under the label `idea` while they're still Fresh In Our Memories :tm:

**Comment by henare** [comment]
I'm going to close this in favour of opening specific issues for the bits we want to open. I can't think of any right now but please add any you can.
