### ISSUE TITLE
Promote batch requests so that many more requests are made

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#606]
- [ ] is there anyone who's using the site currently who could be making batch requests? If so, make sure they know about the feature.
- [ ] tell more people about batch requests

Batch requests are an easy way to generate lots of requests, but only a few people have used them. If we could get more people using the feature, then many more requests would be made and lots of documents would be released :)

**Comment by henare** [comment]
I've asked the Alaveteli list about this https://groups.google.com/forum/#!topic/alaveteli-users/vW5re24Od3s

**Comment by henare** [comment]
We've decided this means emailing everyone using Right To Know. We've emailed one of the people that have used batch requests to see if they will write a blog post we can send out.

**Comment by equivalentideas** [comment]
> If we could get more people using the feature, then many more requests would be made and lots of documents would be released :)

After @henare mentioned batch requests at the [OpenAustralia Foundation Pub Meet](https://www.meetup.com/OpenAustralia-Foundation/events/230629187/) one of the attendees made a request to 149 authorities ❤️  https://www.righttoknow.org.au/info_request_batch/6

**Comment by henare** [comment]
I wrote a little [blog post about batch requests](https://www.openaustraliafoundation.org.au/2016/11/07/how-to-send-your-freedom-of-information-request-to-many-authorities-at-once/). I'm hoping the title is search engine friendly so it continues to be useful.

I've also setup a mailing to people with accounts on RTK which will go out tomorrow morning our time.

**Comment by equivalentideas** [comment]
> I wrote a little blog post about batch requests.

Great work @Henare 👍
