### ISSUE TITLE
Add the Tasmanian FOI jurisdiction

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#615]
Following steps in the readme https://github.com/openaustralia/righttoknow#adding-more-jurisdictions

The tassie FOI act is the [Right to Information Act 2009](http://www.austlii.edu.au/au/legis/tas/consol_act/rtia2009234/).

**Comment by equivalentideas** [comment]
Reviews of Right To Information decisions in Tasmania and handled by Ombudsman Tasmania 
http://www.ombudsman.tas.gov.au/right_to_information/right_to_information_application_for_assessed_disclosure_application_form

**Comment by equivalentideas** [comment]
Looks like there’s fees :( see http://www.workcover.tas.gov.au/workcover_tasmania/obtaining_information

> A minimum search fee of $37.00 (includes GST) applies with an additional charge of $37.00 per hour thereafter for processing. Information can be provided by CD, email or photocopy. Charges apply.

**Comment by henare** [comment]
> Looks like there’s fees :(

Here's all the [important differences in FOI laws around Australia](https://docs.google.com/spreadsheets/d/1KP2efKvCP3jAknTGYUOq8EYpjNElcWDhb0qUX2Rm4lg/edit#gid=0).

**Comment by equivalentideas** [comment]
Done in https://github.com/openaustralia/righttoknow/pull/622
