### ISSUE TITLE
Add other ways you can help out

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#617]
https://www.righttoknow.org.au/help/credits#helpus
- Adding annotations to help requesters
- Becoming an administrator to help run the site (replying to email?)

**Comment by equivalentideas** [comment]
I've added these two points in https://github.com/openaustralia/righttoknow/compare/64fa94c49...f4ac913f8303

**Comment by equivalentideas** [comment]
If you think of more ways to help than are currently listed, reopen this and add em :)
