### ISSUE TITLE
Intro paragraphs on homepage have different font size 

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#620]
I think they're supposed to be the same:

![selection_001](https://cloud.githubusercontent.com/assets/48945/18427774/92d91f9c-790d-11e6-8225-92e336cfd75e.png)

**Comment by Keerti-Gautam** [comment]
Hi @henare ,
Went through the website and found this issue is still persistent. I think I can get it sorted within a few days (currently trying to learn more about your organisation and reading the website's content)

**Comment by EkaterinaSemenova** [comment]
Hi @henare, I believe #682 should fix this

**Comment by equivalentideas** [comment]
Closed by @EkaterinaSemenova with https://github.com/openaustralia/righttoknow/pull/682

![screen shot 2017-04-19 at 2 55 51 pm](https://cloud.githubusercontent.com/assets/1239550/25163830/5d400d50-2510-11e7-854e-58cedb2d54d6.png)
