### ISSUE TITLE
Show the top recent and all time requesters and annotators

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#645]
To help us find potential new administrators (#643) and people getting stuff done who can share their knowledge and be encouraged to do more (#557), it would be helpful to know when someone comes along and starts annotating lots of requests or making lots of requests. This is a signal we can then investigate further to learn about the person.

Initially this can take a similar form to the Request Classification Game that shows “Top recent players” and “Top all time players”. We need to be careful not to incentivise people to just make a high quantity of requests/annotations. This shouldn't initially be something that users are encouraged to look at, and is for us admins. It would say something like “Top recent annotators”, “All time most frequent annotators” or something...

![screen shot 2016-10-05 at 1 44 08 pm](https://cloud.githubusercontent.com/assets/1239550/19099460/524574ba-8b02-11e6-97e5-079f1a882c53.png)

As a first pass we images this being four tables:
- people who've made the most requests recently
- people who’ve made the most requests over all
- people who've made the most annotations recently
- people who've made the most annotations over all

**Comment by equivalentideas** [comment]
We would also like to make the requests/annotations per day available via a JSON API to feed things to publish the data like [Jacaranda](https://github.com/openaustralia/jacaranda).

**Comment by equivalentideas** [comment]
“Recent” in the request classification game [means the last 28 days](https://github.com/mysociety/alaveteli/blob/develop/app/controllers/request_game_controller.rb#L33). [The query to get the results](https://github.com/mysociety/alaveteli/blob/develop/app/models/request_classification.rb#L20) is very similar to how [we got annotators information recently](https://github.com/mysociety/alaveteli/issues/1107#issuecomment-251030182):

```
Comment.joins(:user).group(:user).order("count_all DESC").limit(10)
.count.each { |k,v| puts "#{k.name}: #{v}" }
```

**Comment by equivalentideas** [comment]
One way to do this would be to make a new page in our theme that just ran queries like these ☝️ to produce these tables. But that doesn't give us the JSON data we want as well.

Alternatively we could produce a JSON version of the search results (by adding it internally or scraping it) and use that to compile our tables on an external site. That seems logical with this being just an experiment at the moment.

**Comment by equivalentideas** [comment]
> One way to do this would be to make a new page in our theme that just ran queries like these ☝️ to produce these tables. But that doesn't give us the JSON data we want as well.

I'm just going to make these tables for starters and see what we turn up.

**Comment by equivalentideas** [comment]
@henare is back and we’re decided to make a new, temporary/experiment page in the Right To Know that has these tables. The controller action will also respond to .json with the structured data for that page. The html format of it will have the nice tables with the information we want.

**Comment by equivalentideas** [comment]
I'm going to do the html page while Henare gets the data together.

**Comment by equivalentideas** [comment]
Here's the branch for working on this https://github.com/openaustralia/righttoknow/tree/people_experiment

**Comment by equivalentideas** [comment]
We made it https://www.righttoknow.org.au/people 🎉 

![screen shot 2016-10-05 at 6 11 37 pm](https://cloud.githubusercontent.com/assets/1239550/19104250/3f074386-8b27-11e6-8bb6-3f9cbad697c1.png)
![screen shot 2016-10-05 at 6 11 46 pm](https://cloud.githubusercontent.com/assets/1239550/19104251/3f1089aa-8b27-11e6-9204-6b4bcab632f2.png)

**Comment by henare** [comment]
And there's even an API :neckbeard: https://www.righttoknow.org.au/people.json

**Comment by equivalentideas** [comment]
I've set slack to remind us to have a look at this every two weeks:

> :thumbsup: I will remind #righttoknow to “check https://www.righttoknow.org.au/people” at 9am every other Thursday (next occurrence is October 20th). Cancel · View existing reminders
