### ISSUE TITLE
Total number of requests for public bodies on /body_statistics includes hidden requests

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#648]
While the page says “Unclassified or hidden requests are not counted.”, the charts get data using the `info_requests_count` attribute rather than the `info_requests_visible_count` https://github.com/openaustralia/alaveteli/blob/production/app/models/public_body.rb#L604-L607

**Comment by equivalentideas** [comment]
We should raise this upstream.

**Comment by henare** [comment]
Raised upstream https://github.com/mysociety/alaveteli/issues/3532.
