### ISSUE TITLE
Broken link: "Statement of IP Principles for Australian Government Agencies"

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#649]
https://www.righttoknow.org.au/help/requesting#reuse

Thanks to the spammy looking email that pointed this out :wink:

**Comment by Anishka0107** [comment]
I guess it should point to the link http://www.ags.gov.au/publications/express-law/el125.pdf
Am I right?

**Comment by katska** [comment]
This is a duplicate, @mlandauer updated in this commit https://github.com/openaustralia/righttoknow/commit/d4064088cdf464ec7f6bddfcf459059c42a80e4e

**Comment by mlandauer** [comment]
Yup looks like a duplicate to me. Closing.
