### ISSUE TITLE
Logo missing on HTML version of attachments on older requests

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#656]
e.g. https://www.righttoknow.org.au/request/1344/response/4557/attach/html/6/FOI15%20216%20Document%201%20Enforcement%20Agency%20Applications%20REDACTED.PDF.html

![selection_010](https://cloud.githubusercontent.com/assets/48945/20250227/e9bbbf8a-aa5f-11e6-87d1-d48710abe3cc.png)

**Comment by henare** [comment]
My guess is that this is a similar issue to https://github.com/openaustralia/righttoknow/commit/9095a58ec86c7759212adc787e27be492e0541dc.

@equivalentideas can you please take a look?

**Comment by equivalentideas** [comment]
> My guess is that this is a similar issue to 9095a58.

Sadly it's not, the this uses the same helper (`image_tag "logo.png"`) as the homepage logo. But on production, the HTML document page is uses a link with a different cache busting hash :S

```
/assets/logo-c10e4acf57898c4d0aee43bcb0506b8f.png
```

instead of

```
/assets/logo-f3fa7778243ae82238f6e96f9dc2763d.png
```

Now to workout why that is.

**Comment by equivalentideas** [comment]
Looks like a caching problem. Older requests are using the wrong hash, where as recent ones are sweet:

https://www.righttoknow.org.au/request/2371/response/7011/attach/html/2/HEPPP%20TOR%20deliverables.pdf.html

![screen shot 2016-11-14 at 12 24 52 pm](https://cloud.githubusercontent.com/assets/1239550/20250684/7c50e1b8-aa65-11e6-818b-72363477ed2d.png)
![screen shot 2016-11-14 at 12 25 19 pm](https://cloud.githubusercontent.com/assets/1239550/20250685/7c57a052-aa65-11e6-8a29-ff4264a7ca8b.png)

**Comment by equivalentideas** [comment]
This rang a bell, we've seen this before on https://github.com/openaustralia/righttoknow/issues/474

@henare fixed with:

> I've deleted the cache by removing these two directories:
> 
> /srv/www/www.righttoknow.org.au/shared/cache/attachments_production/
> /srv/www/www.righttoknow.org.au/shared/cache/views/
> 
> This was long overdue as we fixed a bug a while ago and also changed the design recently and none of these changes were reflected in already-cached HTML views. So we need to remember to do this when we make changes to the HTML view stuff.

We changed the logo file 4 months ago (in https://github.com/openaustralia/righttoknow/commit/b2f30b85fbad65ac27090dbd3a8b9a4fd255599e) so that's what's happened.

I'll clear that cache so the pages update.

This is a real drag because we're gonna keep missing this. I'll do a dig around upstream and open an issue if necessary.

**Comment by equivalentideas** [comment]
Fixed, with same method as ☝️
