### ISSUE TITLE
Rebuild AdWords campaigns

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#660]
This AdWords campaign covers a bunch of different ideas which are separated under Ad Groups. There's Ad Groups for general request keywords like “foi laws” and then a few different groups for batches of authority names. There's a group for authorities that are boards, one for councils, one for ministers’ offices, and a few other kind of misc ones. All the ads shown are the same.

![screen shot 2016-11-21 at 4 52 00 pm](https://cloud.githubusercontent.com/assets/1239550/20472183/ad8ceb5e-b00b-11e6-8c9e-3a0345b99ff6.png)
![screen shot 2016-11-21 at 4 52 47 pm](https://cloud.githubusercontent.com/assets/1239550/20472082/f3582afa-b00a-11e6-8522-bf5d639e2591.png)

The way to clean this up is to make a campaign for each theme of ad for the project, e.g.

* one for people trying to learn about FOI in Australia (this could breakdown into state ad groups for each jurisdictions laws?)
* one for authorities, with an adgroup for each authority (and ad that links to that authorities page).
* one for each specialised authority ad idea, like a special council one with ad copy about getting council documents for example.

With more granular structure we can:

1. send people to the most relevant url for their search
2. customise ad copy to the topic better.
3. track conversations and manage the campaigns more simply

Relates to #549

**Comment by equivalentideas** [comment]
There's also another campaign, “Right To Know” that includes two ad groups. One has generic keywords around “freedom”, “australia” and “FOI”, the other one is around “How to make an FOI request”.

Neither perform well, and these themes are pretty covered by an ad group in the other Right To Know campaign. When we split that out, we should pause this one.

**Comment by equivalentideas** [comment]
Also note that there are more Right To Know themed Ad Groups under the big “OpenAustralia Projects” campaign. These probably overlap a bit with these campaigns as well. Once all our main themes are up at the campaign level it'll be way easier to manage these and see the duplication.

**Comment by henare** [comment]
Megan advised us to approach this differently, hence the issue title change:

>* Export all current Right to Know keywords and compile in 1 single list
>* Remove all duplicates
>* Re-categorise all keywords into specific Ad Groups based on theme of kw
>* Re-write ad copy at the ad group level to be as relevant as possible to the keyword theme

**Comment by equivalentideas** [comment]
Here's Megan’s full notes on this:

> Sounds like we should look at combining/streamlining the current approach to Right to Know. 

To do this, she recommended building from the keywords up and see what themes emerge, rather than our current Campaign down approach (see under "Process" below).

> * Questions:
>     * What are the key themes that fall under the ‘Right to Know’ banner?
> * With current Campaigns
>     * Right to Know – Agencies
>         I would make an Ad Group for each individual Agency and ensure the ad copy for each Ad Group was tailored to that relevant Agency.
>     * Right to Know - FOI Made Easy + Right to Know – Make an FOI Request
>       * These campaigns could be combined into 1 and the keywords should be reorganised into tighter Ad Group themes
>       * Ad Copy should then be tailored specifically to each Ad Group

> Process: 
> * Export all current Right to Know keywords and compile in 1 single list
> * Remove all duplicates
> * Re-categorise all keywords into specific Ad Groups based on theme of kw
> * Re-write ad copy at the ad group level to be as relevant as possible to the keyword theme

Megan did an example run through this for us, making this example spreadsheet:
https://docs.google.com/spreadsheets/d/1O3WRVO0Nj3-Hhzv__Mb-XXg-KEftZVEv3C9P4XTF63k/edit#gid=1277122262

**Comment by henare** [comment]
I think we've now either disabled the campaigns mentioned here or we've extracted tasks into other issues so I'm going to close this.

**Comment by equivalentideas** [comment]
Here's two of the specific campaign ideas we've extracted:

* Ads for people search an authorities name https://github.com/openaustralia/righttoknow/issues/677
* Ads for people searching about general government information and state laws https://github.com/openaustralia/righttoknow/issues/665

That's a start and they might even be broken down further.
