### ISSUE TITLE
Test variation of “FOI made easy” Google AdWords ad: “Freedom of Information - Made Easy”

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#661]
We just set up a variation of our add to text if having the full “Freedom of Information” in the title resulted in more clicks and conversions.

We should check back to see how this goes in a week of so.
![screen shot 2016-11-21 at 4 17 13 pm](https://cloud.githubusercontent.com/assets/1239550/20471442/f5298ef0-b005-11e6-9d12-c65adc8bf15c.png)

Note that we've been a bit naughty and also make “Made Easy” capitalised.

**Comment by equivalentideas** [comment]
The variation with the full "Freedom of Information" is doing much better.

* It's getting served 63.79% of the time.
* Has a 7.57% Click Through Rate, as opposed to 3.46% for the control.
* It has a slightly higher average position: 1.2 vs 1.9.

Tiny conversation rate 👇 though, on both.

![screen shot 2017-01-11 at 12 13 00 pm](https://cloud.githubusercontent.com/assets/1239550/21831372/5ea44e4c-d7f7-11e6-89d1-9fe891634500.png)

I've going to remove the control ad, this variation wins.

**Comment by equivalentideas** [comment]
I've opened a new issue for improving the conversion https://github.com/openaustralia/righttoknow/issues/661

**Comment by garethrees** [comment]
Super interesting! Just added a link from our experiments repo https://github.com/mysociety/alaveteli-experiments/commit/fbf76b0e9b1b68c552b904c3d7375b81d07b605d – hope that's okay?

**Comment by equivalentideas** [comment]
@garethrees of course! That's what it's here for :) It's great to be able to share this stuff.
