### ISSUE TITLE
Why are there so many duplicate ads under the "Right To Know - Agencies" adwords campaign?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#663]
Should there be removed?

**Comment by equivalentideas** [comment]
I think this is just an artifact of https://github.com/openaustralia/righttoknow/issues/660 where we have lots of ad groups for this. Each ad group has an ad, which are all the same, so at the campaign level they look like duplicates.

Once we sort out that issue, this should be resolved.

**Comment by henare** [comment]
This campaign has now been disabled and it's being rebuilt as part of #677 so I'll close this.
