### ISSUE TITLE
"Make a request" button on 2 lines in 0.26

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#669]
![image](https://cloud.githubusercontent.com/assets/6841582/22142861/dd372e54-df32-11e6-9f76-8440b644ebf4.png)

**Comment by Keerti-Gautam** [comment]
Hi @benrfairless 
Is this issue still persistent? I couldn't see it when I searched for "Department" in 'Find an Authority' on the website. My search is [here](https://www.righttoknow.org.au/select_authority?utf8=%E2%9C%93&query=Department&bodies=1&commit=Search) and the screenshot is below ![below](https://cloud.githubusercontent.com/assets/19797779/24512224/a333a388-158b-11e7-9716-e980e534c61e.png)

I feel this is resolved and should be closed.

**Comment by Keerti-Gautam** [comment]
Just saw this page in the development server, and it looks exactly like it is shown in @benrfairless screenshot. Whereas, it was fine on the live site. 
@equivalentideas Could you please clarify?

Thanks! :smile:

**Comment by benrfairless** [comment]
We run an older version of Alaveteli in production. This bug was created to show what we need to fix in order to upgrade our version of Alaveteli.

**Comment by equivalentideas** [comment]
Fixed by @Keerti-Gautam in https://github.com/openaustralia/righttoknow/pull/685
