### ISSUE TITLE
Request Preview is out of line in 0.26

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#670]
Google Chrome running 0.26 with our current theme:
![image](https://cloud.githubusercontent.com/assets/6841582/22142958/3d8af470-df33-11e6-9232-7b76daa57837.png)

**Comment by Keerti-Gautam** [comment]
Hi @benrfairless @equivalentideas 
This was a feature of Alaveteli and I got it changed there (by creating a [PR](https://github.com/mysociety/alaveteli/pull/3884) which got merged today), and it would be included in the next version of Alaveteli (0.29). 
However, we at Right To Know would be upgrading to 0.26 version so I am going to make a PR here so this improvement is available to us. 
Kindly suggest where do I change this? In 0.26-upgrade branch or in production branch?

**Comment by equivalentideas** [comment]
@Keerti-Gautam If you see this issue on the current production branch, make the fix there :) If it's just something that terns up in the upgrade, then make it on the upgrade branch.

Great job contributing this fix upstream! Congratulations on having had a PR merged to Alaveteli 🏆  

When you make this temp fix in our theme, [as suggested](https://github.com/mysociety/alaveteli/pull/3884#issuecomment-292203899) please add a comment like:

```
// TODO: Remove this once 9829b113ad16515cdd451a30154e35a0bc1bd3b2 is merged
// see https://github.com/mysociety/alaveteli/pull/3884#issuecomment-292203899
```

—so we know to remove the temp fix when we get your fix from upstream.

**Comment by equivalentideas** [comment]
Closed by https://github.com/openaustralia/righttoknow/pull/694
