### ISSUE TITLE
Search results counts and pagination is wrong on the first page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#673]
Search for requests sent between two dates, e.g. https://www.righttoknow.org.au/search/variety:sent%2030/1/2017..12/2/2017/requests .

On [the first page](https://www.righttoknow.org.au/search/variety:sent%2030/1/2017..12/2/2017/?page=1) it says “**FOI requests 1 to 25 of 1036**” and the pagination shows there's lots of pages to look through:

![screen shot 2017-02-15 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/1239550/22959492/f0a2e980-f38a-11e6-9ca4-f7c8e1ab8a22.png)

Go to [the second page](https://www.righttoknow.org.au/search/variety:sent%2030/1/2017..12/2/2017/?page=2). It now says “**FOI requests 26 to 35 of 35**” which is the correct number of requests. The pagination is now as you'd expect:

![screen shot 2017-02-15 at 2 27 32 pm](https://cloud.githubusercontent.com/assets/1239550/22959495/f7ea4878-f38a-11e6-8d17-ecd970058092.png)

This isn't a problem on whatdotheyknow, so I haven't raised this upstream. See https://www.whatdotheyknow.com//search/variety:sent%2030/1/2017..12/2/2017/requests

**Comment by henare** [comment]
I think this is the upstream issue: https://github.com/mysociety/alaveteli/issues/456

**Comment by equivalentideas** [comment]
Yep that looks like it 😢 raised 5 years ago.

**Comment by auxesis** [comment]
FYI mysociety/alaveteli#456 is marked as closed, courtesy of mysociety/alaveteli#4052.

**Comment by equivalentideas** [comment]
> FYI mysociety/alaveteli#456 is marked as closed, courtesy of mysociety/alaveteli#4052.

@auxesis It reads to me that the issue is being closed as 'wont fix' https://github.com/mysociety/alaveteli/issues/456#issuecomment-322976225

**Comment by benrfairless** [comment]
I have attempted to replicate this and it appears to no longer be an issue.
