### ISSUE TITLE
JSON feed returns RSS :S

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#674]
This is the JSON url described in the head here:

```
<link rel="alternate" type="application/json" title="JSON version of Requests or responses matching your saved search" href="https://www.righttoknow.org.au/feed/search/variety:sent%2030/1/2017..12/2/2017.json">
```

https://www.righttoknow.org.au/feed/search/variety:sent%2030/1/2017..12/2/2017.json

It returns an RSS feed.

**Comment by henare** [comment]
I [fixed this upstream](https://github.com/mysociety/alaveteli/pull/3485), it's in the next release.

**Comment by benrfairless** [comment]
Closed by https://github.com/mysociety/alaveteli/pull/3485
