### ISSUE TITLE
E-Voting using Blockchain

### ISSUE THREAD

**Issue by Shreya1771** [openaustralia/righttoknow#691]
Hi, 
I'm Shreya Sonawane, a second year graduates in Information Technology from SRM University. Going in depth into the Open Australia organization I have found lots of things related to laws and right to vote, right to know and many more which all of them comes under the OA organization.

So now coming to the e-voting after lot of research I have found that we can also create a e-voting system website or a platform using block-chain technology in python using unique identification of the person for each one vote. In one of my Hackathon at government in India I was shortlisted for this idea build a back-end prototype as well. Looking forward for the positive response.

Thank you 
Shreya

**Comment by equivalentideas** [comment]
Hi @Shreya1771 That does sound like an interesting project @mario-areias is quite interested in parts of improving and opening the technology around elections.

This repo is just for discussions around Right To Know, so I'll close this. Have you written about this somewhere? I could send that through to see if anyone round our camp is interest in hacking on this with you.

**Comment by Shreya1771** [comment]
@equivalentideas should I write a blog for this what tools and technology or a pdf and just share you?

**Comment by equivalentideas** [comment]
@Shreya1771 I think a blog post is nice since then people online can stumble across it and be inspired by your ideas :)
