### ISSUE TITLE
Zip files of a request's correspondence are corrupt

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#696]
Clicking _Download a zip file of all correspondence_ on any request works, the resulting Zip file looks OK but trying to open any of the files doesn't work.

We were contacted by a user with this problem and testing locally GNOME Archive Manager it doesn't work either. I tried unzipping from the Linux command line with `unzip` but weirdly that did work!

**Comment by mlandauer** [comment]
I tried this recently and it seems fine. So, closing
