### ISSUE TITLE
Link to contact us when request marked for administrator attention doesn't go to the right place

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#697]
When a request has already been marked for administrator attention the sidebar item about reporting the request changes to this:

![selection_001](https://user-images.githubusercontent.com/48945/27322152-513d99ea-55e0-11e7-9754-83f99fb3b4b1.png)

The contact us link goes to `/help/requesting` page, not `/help/contact` as I think it should.

**Comment by benrfairless** [comment]
This no longer happens due to the new theme. Closing!
