### ISSUE TITLE
NGINX proxy has body size set too small

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/righttoknow#705]
We're finding that people uploading even small documents (~3.8Mb) are getting a `413 Request Entity Too Large` error.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_eggt)

**Comment by benrfairless** [comment]
This issue remains unresolved :(

**Comment by benrfairless** [comment]
Confirmed error occurs in Test and in Production

413 Request Entity too large

https://www.test.righttoknow.org.au/request/testing_uploads for testing

Limit is set at 1MB

Will review this later tonight
