### ISSUE TITLE
House Rules

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#712]
Our sister site at What Do they Know has house rules and a better help page:

https://www.whatdotheyknow.com/help/principles
https://www.whatdotheyknow.com/help/how
https://www.whatdotheyknow.com/help/house_rules
https://www.whatdotheyknow.com/help/complaints

Maybe it’s time we start looking at this.

**Comment by katska** [comment]
@benrfairless sadly I am locked out of @kat due to dead drive disaster with my 2fa codes .... but I can reply as @katska

**Comment by benrfairless** [comment]
This is now done ❤️
