### ISSUE TITLE
Allow a request to be split between different departments

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#723]
It's possible for a request to be partially transferred, so 2 departments are working on the same request.

At the moment we only support one department per request.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_l5v9)

**Comment by mlandauer** [comment]
This sounds like a question / feature request for the upstream Alaveteli

**Comment by benrfairless** [comment]
https://github.com/mysociety/alaveteli/issues/8300
