### ISSUE TITLE
PDF Document showing as corrupt on multiple requests.

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#731]
Refer to the PDFs sent by the Department on 26/11/2020 on these requests:

https://www.righttoknow.org.au/request/6822
https://www.righttoknow.org.au/request/6823
https://www.righttoknow.org.au/request/6828
https://www.righttoknow.org.au/request/6829
https://www.righttoknow.org.au/request/6889

They don't open in Chrome or IE and show as Corrupt. The PDF in Front is fine. When I upload the PDF in Front to RTK Test I get the same error message. 

I've managed to work around the issue by uploading the document to a PDF upload site and sharing that link.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_37n5x)

**Comment by benrfairless** [comment]
@mlandauer these were the requests that weren’t working. I’ve checked each of them and they are working fine now.

**Comment by mlandauer** [comment]
@benrfairless wonderful. Thank you!
