### ISSUE TITLE
Review and modify changed templates

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#734]
Review if we have changed any of the below templates. If so, then see if we need to modify them to make them work under the new version.

**Comment by benrfairless** [comment]
**0.26.0.0**
app/views/admin_general/_admin_navbar.html.erb
app/views/admin_general/debug.html.erb
app/views/admin_general/index.html.erb
app/views/admin_public_body/edit.html.erb
app/views/admin_public_body/import_csv.html.erb
app/views/admin_public_body/new.html.erb
app/views/admin_user/_user_table.html.erb
app/views/admin_user/index.html.erb
app/views/comment/_single_comment.html.erb
app/views/contact_mailer/add_public_body.text.erb
app/views/contact_mailer/to_admin_message.text.erb
app/views/contact_mailer/update_public_body_email.text.erb
app/views/contact_mailer/user_message.text.erb
app/views/general/_advanced_search_tips.html.erb
app/views/general/_footer.html.erb
app/views/general/_frontpage_hero.html.erb
app/views/general/_localised_datepicker.html.erb
app/views/general/_new_request.html.erb
app/views/general/_popup_banner.html.erb
app/views/general/blog.html.erb
app/views/general/search.html.erb
app/views/info_request_batch_mailer/batch_sent.text.erb
app/views/layouts/admin.html.erb
app/views/layouts/default.html.erb
app/views/layouts/no_chrome.html.erb
app/views/outgoing_mailer/initial_request.text.erb
app/views/public_body/_body_listing_single.html.erb
app/views/public_body/_list_sidebar_extra.html.erb
app/views/public_body/_search_ahead.html.erb
app/views/public_body/statistics.html.erb
app/views/public_body/view_email.html.erb
app/views/public_body/view_email_captcha.html.erb
app/views/request/_bubble.html.erb
app/views/request/_incoming_correspondence.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_request_listing.html.erb
app/views/request/_sidebar.html.erb
app/views/request/_view_html_stylesheet.html.erb
app/views/request/describe_notices/_requires_admin.html.erb
app/views/request/new.html.erb
app/views/request/select_authorities.html.erb
app/views/request/select_authority.html.erb
app/views/request/show.html.erb
app/views/request_game/play.html.erb
app/views/request_mailer/comment_on_alert.text.erb
app/views/request_mailer/comment_on_alert_plural.text.erb
app/views/request_mailer/new_response.text.erb
app/views/request_mailer/new_response_reminder_alert.text.erb
app/views/request_mailer/not_clarified_alert.text.erb
app/views/request_mailer/old_unclassified_updated.text.erb
app/views/request_mailer/overdue_alert.text.erb
app/views/request_mailer/stopped_responses.text.erb
app/views/request_mailer/very_overdue_alert.text.erb
app/views/track_mailer/event_digest.text.erb
app/views/user/set_crop_profile_photo.html.erb
app/views/user_mailer/already_registered.text.erb
app/views/user_mailer/changeemail_already_used.text.erb
app/views/user_mailer/changeemail_confirm.text.erb
app/views/user_mailer/confirm_login.text.erb

**Comment by benrfairless** [comment]
**0.26.0.1**
app/views/admin_public_body/edit.html.erb
app/views/widgets/show.html.erb

**Comment by benrfairless** [comment]
**0.27.0.0**
app/views/admin_holiday_imports/new.html.erb
app/views/admin_public_body/edit.html.erb
app/views/admin_request/edit.html.erb
app/views/admin_request/show.html.erb
app/views/comment/_single_comment.html.erb
app/views/comment/_single_comment.text.erb
app/views/comment/new.html.erb
app/views/followups/_followup.html.erb
app/views/followups/new.html.erb
app/views/general/_advanced_search_tips.html.erb
app/views/general/_frontpage_search_box.html.erb
app/views/general/_responsive_header.html.erb
app/views/general/_responsive_topnav.html.erb
app/views/general/blog.html.erb
app/views/general/search.html.erb
app/views/info_request_batch/show.html.erb
app/views/layouts/default.html.erb
app/views/public_body/_body_listing_single.html.erb
app/views/request/_after_actions.html.erb
app/views/request/_bubble.html.erb
app/views/request/_describe_state.html.erb
app/views/request/_incoming_correspondence.html.erb
app/views/request/_incoming_correspondence.text.erb
app/views/request/_other_describe_state.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_outgoing_correspondence.text.erb
app/views/request/_request_sent.html.erb
app/views/request/_sidebar.html.erb
app/views/request/_wall_listing.html.erb
app/views/request/describe_notices/_successful.html.erb
app/views/request/hidden.html.erb
app/views/request/new.html.erb
app/views/request/show.html.erb
app/views/user/_user_listing_single.html.erb
app/views/user/banned.html.erb
app/views/user/rate_limited.html.erb
app/views/user/show.html.erb
app/views/widgets/show.html.erb

**Comment by benrfairless** [comment]
**0.27.1.0**
app/views/comment/_single_comment.html.erb
app/views/followups/preview.html.erb
app/views/general/_log_in_bar.html.erb
app/views/general/_nav_items.html.erb
app/views/public_body/_search_ahead.html.erb
app/views/request/_bubble.html.erb
app/views/request/_incoming_correspondence.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_sidebar.html.erb
app/views/request/select_authority.html.erb
app/views/user/bad_token.html.erb

**Comment by benrfairless** [comment]
**0.28.0.0**
app/views/admin_general/debug.html.erb
app/views/admin_public_body_headings/_form.html.erb
app/views/alaveteli_pro/info_requests/_sidebar.html.erb
app/views/alaveteli_pro/info_requests/preview.html.erb
app/views/comment/_comment_form.html.erb
app/views/comment/preview.html.erb
app/views/request/describe_state_message.html.erb
app/views/request/preview.html.erb
app/views/user/_signup.html.erb

**Comment by benrfairless** [comment]
**0.29.0.0**
app/views/admin_comment/edit.html.erb
app/views/admin_general/index.html.erb
app/views/admin_general/timeline.html.erb
app/views/admin_outgoing_message/edit.html.erb
app/views/admin_public_body/show.html.erb
app/views/admin_public_body_categories/_form.html.erb
app/views/admin_request/_some_requests.html.erb
app/views/admin_request/index.html.erb
app/views/admin_request/show.html.erb
app/views/admin_user/_form.html.erb
app/views/admin_user/show.html.erb
app/views/alaveteli_pro/comment/_suggestions.html.erb
app/views/alaveteli_pro/dashboard/_activity_list_item.html.erb
app/views/alaveteli_pro/dashboard/_projects.html.erb
app/views/alaveteli_pro/dashboard/index.html.erb
app/views/alaveteli_pro/draft_info_requests/_draft_info_request.html.erb
app/views/alaveteli_pro/embargo_mailer/expiring_alert.text.erb
app/views/alaveteli_pro/followups/_embargoed_form_title.html.erb
app/views/alaveteli_pro/general/_log_in_bar_links.html.erb
app/views/alaveteli_pro/info_requests/_embargo_info.html.erb
app/views/alaveteli_pro/info_requests/_info_request.html.erb
app/views/alaveteli_pro/info_requests/_request_list.html.erb
app/views/alaveteli_pro/info_requests/_sidebar.html.erb
app/views/alaveteli_pro/info_requests/new.html.erb
app/views/alaveteli_pro/info_requests/preview.html.erb
app/views/alaveteli_pro/public_bodies/_search_result.html.erb
app/views/comment/_single_comment.html.erb
app/views/followups/_followup.html.erb
app/views/followups/preview.html.erb
app/views/general/_log_in_bar.html.erb
app/views/general/_nav_items.html.erb
app/views/general/_responsive_header.html.erb
app/views/general/_responsive_topnav.html.erb
app/views/general/_topnav.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/default.html.erb
app/views/layouts/no_chrome.html.erb
app/views/outgoing_messages/delivery_statuses/show.html.erb
app/views/public_body/_list_sidebar_extra.html.erb
app/views/public_body/_more_info.html.erb
app/views/reports/new.html.erb
app/views/request/_after_actions.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_request_filter_form.html.erb
app/views/request/describe_notices/_error_message.html.erb
app/views/request/describe_notices/_internal_review.html.erb
app/views/request/describe_notices/_not_held.html.erb
app/views/request/describe_notices/_successful.html.erb
app/views/request/describe_notices/_waiting_response.html.erb
app/views/request/describe_notices/_waiting_response_overdue.html.erb
app/views/request/details.html.erb
app/views/request/new.html.erb
app/views/request/preview.html.erb
app/views/request_mailer/stopped_responses.text.erb

**Comment by benrfairless** [comment]
**0.30.0.0**
app/views/admin_comment/index.html.erb
app/views/admin_general/index.html.erb
app/views/admin_general/timeline.html.erb
app/views/admin_public_body/show.html.erb
app/views/admin_user/index.html.erb
app/views/alaveteli_pro/account_mailer/account_request.text.erb
app/views/alaveteli_pro/account_request/new.html.erb
app/views/alaveteli_pro/draft_info_request_batches/_draft_info_request_batch.html.erb
app/views/alaveteli_pro/embargo_mailer/expiring_alert.text.erb
app/views/alaveteli_pro/info_request_batches/_authority_list.html.erb
app/views/alaveteli_pro/info_request_batches/_form.html.erb
app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb
app/views/alaveteli_pro/info_requests/_after_actions.html.erb
app/views/alaveteli_pro/info_requests/_info_request.html.erb
app/views/alaveteli_pro/info_requests/_sidebar.html.erb
app/views/alaveteli_pro/info_requests/preview.html.erb
app/views/comment/preview.html.erb
app/views/contact_mailer/update_public_body_email.text.erb
app/views/followups/preview.html.erb
app/views/general/_footer.html.erb
app/views/general/_header.html.erb
app/views/general/_opengraph_tags.html.erb
app/views/general/_orglink.html.erb
app/views/general/_responsive_header.html.erb
app/views/general/_stylesheet_includes.html.erb
app/views/general/_topnav.html.erb
app/views/general/search.html.erb
app/views/info_request_batch/show.html.erb
app/views/layouts/default.html.erb
app/views/layouts/no_chrome.html.erb
app/views/public_body/_body_listing_single.html.erb
app/views/public_body/_more_info.html.erb
app/views/public_body/show.html.erb
app/views/request/_after_actions.html.erb
app/views/request/_bubble.html.erb
app/views/request/_list_results.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_sidebar.html.erb
app/views/request/_view_html_stylesheet.html.erb
app/views/request_mailer/new_response.text.erb
app/views/track/_track_set.erb
app/views/user/_user_listing_single.html.erb

**Comment by benrfairless** [comment]
**0.31.0.0**
app/views/admin_general/_to_do_list.html.erb
app/views/admin_general/index.html.erb
app/views/admin_raw_email/show.html.erb
app/views/admin_request/show.html.erb
app/views/admin_user/show.html.erb
app/views/alaveteli_pro/account_request/new.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/index.html.erb
app/views/alaveteli_pro/dashboard/_projects.html.erb
app/views/alaveteli_pro/dashboard/index.html.erb
app/views/alaveteli_pro/general/_log_in_bar_links.html.erb
app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb
app/views/alaveteli_pro/info_request_batches/_embargo_info.html.erb
app/views/alaveteli_pro/info_request_batches/_form.html.erb
app/views/alaveteli_pro/info_request_batches/_info_request.html.erb
app/views/alaveteli_pro/info_requests/_embargo_form.html.erb
app/views/alaveteli_pro/info_requests/_embargo_info.html.erb
app/views/alaveteli_pro/info_requests/_form.html.erb
app/views/alaveteli_pro/info_requests/_info_request.html.erb
app/views/alaveteli_pro/info_requests/_new_request_advice.html.erb
app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb
app/views/alaveteli_pro/info_requests/_sidebar.html.erb
app/views/alaveteli_pro/info_requests/index.html.erb
app/views/alaveteli_pro/info_requests/new.html.erb
app/views/alaveteli_pro/info_requests/preview.html.erb
app/views/general/_frontpage_bodies_list.html.erb
app/views/general/_frontpage_requests_list.html.erb
app/views/general/_log_in_bar.html.erb
app/views/general/_responsive_footer.html.erb
app/views/general/exception_caught.html.erb
app/views/notification_mailer/info_request_batches/messages/_overdue.text.erb
app/views/notification_mailer/info_request_batches/messages/_very_overdue.text.erb
app/views/notification_mailer/info_requests/messages/_overdue.text.erb
app/views/notification_mailer/info_requests/messages/_very_overdue.text.erb
app/views/outgoing_mailer/_followup_footer.text.erb
app/views/password_changes/new.html.erb
app/views/request/_act.html.erb
app/views/request/_request_listing_single.html.erb
app/views/request/_request_listing_via_event.html.erb
app/views/request/_request_sent.html.erb
app/views/request/_sidebar.html.erb
app/views/request/details.html.erb
app/views/request/show.html.erb
app/views/track/_rss_feed.html.erb
app/views/user/_signin.html.erb
app/views/user/_signup.html.erb
app/views/user/show.html.erb
app/views/user/sign.html.erb
app/views/users/sessions/show.html.erb

**Comment by benrfairless** [comment]
**0.32.0.0**
app/views/admin_general/_admin_navbar.html.erb
app/views/admin_general/index.html.erb
app/views/admin_incoming_message/_actions.html.erb
app/views/admin_public_body/_form.html.erb
app/views/admin_raw_email/show.html.erb
app/views/admin_request/edit.html.erb
app/views/admin_request/hidden_user_explanation.text.erb
app/views/admin_request/show.html.erb
app/views/admin_user/_user_table.html.erb
app/views/admin_user/show.html.erb
app/views/alaveteli_pro/account_request/index.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/_add_authority_to_draft_button.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/_remove_authority_from_draft_button.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/_search_result.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/_search_results.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/index.html.erb
app/views/alaveteli_pro/dashboard/_no_to_dos.html.erb
app/views/alaveteli_pro/dashboard/index.html.erb
app/views/alaveteli_pro/draft_info_request_batches/_summary.html.erb
app/views/alaveteli_pro/general/_nav_items.html.erb
app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb
app/views/alaveteli_pro/info_request_batches/_embargo_info.html.erb
app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb
app/views/alaveteli_pro/info_request_batches/_message_preview.html.erb
app/views/alaveteli_pro/info_requests/_after_actions.html.erb
app/views/alaveteli_pro/info_requests/_embargo_extension_form.html.erb
app/views/alaveteli_pro/info_requests/_embargo_form.html.erb
app/views/alaveteli_pro/info_requests/_embargo_info.html.erb
app/views/alaveteli_pro/info_requests/_message_preview.html.erb
app/views/alaveteli_pro/info_requests/_no_requests.html.erb
app/views/alaveteli_pro/info_requests/_sidebar.html.erb
app/views/alaveteli_pro/info_requests/index.html.erb
app/views/alaveteli_pro/plans/index.html.erb
app/views/alaveteli_pro/plans/show.html.erb
app/views/alaveteli_pro/subscriptions/index.html.erb
app/views/api/request_events.atom.builder
app/views/followups/_followup.html.erb
app/views/general/_log_in_bar.html.erb
app/views/general/_opengraph_tags.html.erb
app/views/general/_popup_banner.html.erb
app/views/general/_responsive_header.html.erb
app/views/general/_responsive_stylesheets.html.erb
app/views/general/_responsive_topnav.html.erb
app/views/info_request_batch/show.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/default.html.erb
app/views/notification_mailer/info_requests/messages/_very_overdue.text.erb
app/views/notification_mailer/very_overdue_notification.text.erb
app/views/public_body/show.html.erb
app/views/reports/new.html.erb
app/views/request/_after_actions.html.erb
app/views/request/_incoming_correspondence.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_request_subtitle.html.erb
app/views/request/describe_notices/_waiting_response.html.erb
app/views/request/describe_notices/_waiting_response_overdue.html.erb
app/views/request/details.html.erb
app/views/request/new.html.erb
app/views/request/show.text.erb
app/views/request_mailer/very_overdue_alert.text.erb
app/views/user/_show_user_info.html.erb
app/views/user/_signup.html.erb
app/views/user/rate_limited.html.erb
app/views/user/set_draft_profile_photo.html.erb
app/views/user/set_profile_about_me.html.erb
app/views/user/show/_show_profile.html.erb
app/views/user_profile/about_me/edit.html.erb

**Comment by garethrees** [comment]
If you're comfortable with vim, I wrote up a [wiki page and recorded a screencast](https://github.com/mysociety/alaveteli/wiki/Reconcile-changes-between-wdtk-and-whatdotheyknow-theme) demoing some tools I use to help make this process a little easier.
