### ISSUE TITLE
Upgrade to Alaveteli 0.38.3.0, Ubuntu 18.04, Ruby 2.6.6, modernise theme, update content and switch on Alaveteli Pro

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/righttoknow#749]
To do the upgrade we have to do a bunch of things in a particular order. This is an attempt to document that to keep of track of things.

- [x] Upgrade theme to work with version 0.34.0.0 of Alaveteli
- [x] Deploy 0.34.0.0 to staging with Ruby 2.5.8
- [x] Test everything in staging
- [x] Deploy 0.34.0.0 to production with Ruby 2.5.8
- [x] Upgrade server to ubuntu 18.04
- [x] Deploy latest version (0.38.x.x) to staging using Ruby 2.6.6
- [x] Test latest version
- [x] Deploy latest version to production
- [x] Rebuild our theme from scratch using latest alavetelitheme as a base which has much cleaner design - mainly update colour scheme and icon
- [ ] Update wording on help pages based on Ben's PRs and look to other Alaveteli instances for inspiration.
- [x] Test on staging before rolling this out to production
- [x] Switch on Alaveteli Pro

We're currently on Alaveteli 0.25.x.x using Ruby 2.0.0 with the server running Ubuntu 16.04.

We want to upgrade to Alaveteli 0.38.3.0 using the latest version of Ruby we can. That version of Alaveteli only supports (for Ubuntu) 18.04 so we need to use that.

We can't upgrade directly to the version of Alaveteli we want because we need to do an OS upgrade and we definitely don't want to do those two things at the same time.
 
So it's much safer for us to be upgrading to Alaveteli 0.34.0.0 first because it is the last major version of Alavateli that supports both Ubuntu 16.04 and 18.04.

**Comment by mlandauer** [comment]
One thing I didn't say above is the official advise is that you should upgrade to each major version of Alaveteli individually. There are about 13 major versions between where we are currently and where we want to go. It's just a world of crazy to do that step by step so we're going to take some shortcuts and jump many major versions at a time. Even with that there are still many, many steps to this process.

**Comment by mlandauer** [comment]
I had to take a break from doing this work (to fix issues on openaustralia.org.au) and with a little time away to reflect I think doing the upgrade step by step major version by major version is long-winded but will be safer in the sense that we will be deploying changes to production in smaller steps and more frequently.

I could even do one major version upgrade a day and within 3 weeks the thing would be upgrade to where we want to be! :-)

**Comment by benrfairless** [comment]
That would be really good. I like that idea a lot as I’m sure there are steps we will miss.

--- original message ---
On 12 January 2021, 9:51 am AWST notifications@github.com wrote:



I had to take a break from doing this work (to fix issues on openaustralia.org.au) and with a little time away to reflect I think doing the upgrade step by step major version by major version is long-winded but will be safer in the sense that we will be deploying changes to production in smaller steps and more frequently.

I could even do one major version upgrade a day and within 3 weeks the thing would be upgrade to where we want to be! :-)

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by mlandauer** [comment]
First step done - upgraded Alaveteli to 0.25.0.15 in staging and production from the mysociety repo. We're now running off of the official repo rather than our forked code. Note that now the correct version is shown in the admin panel at https://www.righttoknow.org.au/admin/debug

**Comment by mlandauer** [comment]
We are now at 0.26.0.9 in production and staging. In the upgrade notes "Install the geoip-database-contrib package to automatically fetch latest geoip databases." - that didn't work. It had trouble downloading files and so failed. Didn't do "You can improve the speed of your site by making sure that far-future expiration dates are being set on static assets - see the examples in the example config files (config/ httpd.conf-example and config/nginx.conf.example)." because a quick test with Google lighthouse didn't seem to show any big problems so not worth the effort I think

**Comment by mlandauer** [comment]
There's a few small styling issues which I might try to fix by bringing in changes I made to the theme for 0.38

**Comment by mlandauer** [comment]
Now production and staging have been upgraded from ruby 2.0.0 to 2.3.0 which is the latest version supported by alaveteli 0.26.0.9.

**Comment by mlandauer** [comment]
Now have upgraded production and staging to Alaveteli 0.27.1.2. Had to do a bunch of stuff with the theme to make it all work. The upside is that the theme has been refactored in places (mostly header and footer) to bring it closer in line with the templates being used in the current version of Alaveteli. This will make ongoing upgrades a bit easier hopefully too.

One bit that didn't work in either staging or production was running "bundle exec rake temp:populate_request_due_dates". 
```
deploy@ip-172-31-43-31:/srv/www/production/current$ bundle exec rake temp:populate_request_due_dates
rake aborted!
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (6754258, /request/holding_pen, null, InfoRequest, 1).
: INSERT INTO "purge_requests" ("created_at", "model", "model_id", "url") VALUES ($1, $2, $3, $4) RETURNING "id"
```
It looks suspiciously from the [changelog](https://github.com/mysociety/alaveteli/blob/master/doc/CHANGES.md) like there was a bug with that rake task for 0.27.0.0 which was attempted to be fixed in 0.27.0.1 but I'm guessing introduced another bug?

Also in upgrading the theme it looked like some sensible changes were introduced in the default which I merged into the theme. So, now there's a "how it works" section on the home page and the list of recent applications on the home page is now significantly simpler to read.

**Comment by mlandauer** [comment]
Now staging and production are up to Alaveteli 0.28.0.10. In the process there were some weird asset pipeline issues to deal with as well as a bundler version issue and I merged in changes from the main app for the application config so that should be easier to manage from here on in.

**Comment by mlandauer** [comment]
Now production and staging are at Alaveteli 0.29.0.2. There's a problem with the statistics page (which still worked on 0.28.0.10). I'll look at that now

**Comment by mlandauer** [comment]
The stats page is now working again in production. In staging I assume it's broken because there's no data to display ;-)

**Comment by mlandauer** [comment]
Staging has now been upgrade to 0.30.0.5. So far so good. I think that's enough for today. Monday will be upgrading production

**Comment by mlandauer** [comment]
Upgraded to 0.30.0.5 in production. Need to check that everything still works with `VARNISH_HOST` not set

**Comment by mlandauer** [comment]
Removed the VARNISH_HOST setting for production and staging. So far everything is still working

**Comment by mlandauer** [comment]
Upgraded to 0.31.0.4 on staging and production

**Comment by mlandauer** [comment]
Upgraded to 0.32.0.2 in staging and production. Explicitly set the list of popular bodies for the front page because apparently *not* doing that is slow. That way we also have a more reasonably sized list. Also I enabled optional two factor auth.

There is also now a setting EXTERNAL_REVIEWERS which allows you to set an email address for an external review body. The hassle in our case is we have multiple jurisdictions with different review bodies so that won't work. Probably could work with a bit more theme magic but maybe we should wait until we're at the latest version of alaveteli before we do that? I'll create a separate issue for that.

**Comment by mlandauer** [comment]
Issue logged for `EXTERNAL_REVIEWERS` at https://github.com/openaustralia/righttoknow/issues/752

**Comment by mlandauer** [comment]
Have disabled the two factor auth again because it looks like it's based on a one-time password where it gives you a password, you do an action and then it gives you a new password. Eek. The usability of this isn't great and I would be concerned for the support impact it might have.

Hopefully there is a better implementation coming in later versions? It seems unlikely but it's worth hoping for that.

**Comment by mlandauer** [comment]
Upgraded to Alaveteli 0.33.0.0 in staging and production

**Comment by mlandauer** [comment]
Upgraded to Alaveteli 0.34.0.1 in staging and production!

**Comment by mlandauer** [comment]
Upgraded ruby to 2.6.6 in staging and production. This is the latest version that Alaveteli 0.34.0.1 supports.

**Comment by mlandauer** [comment]
Updated the /etc/init.d scripts to get rid of the varnish purge script which is no longer used and the notifications have been reworked so there is a new script for that

**Comment by benrfairless** [comment]
It looks like the Captcha function still isn’t working after the upgrade to 0.34.0.1. I’ve created a new set of keys and invited you to them, but I don’t know how to update them in the Infrastructure section.

**Comment by mlandauer** [comment]
Is this for the captcha on the contact form?

> It looks like the Captcha function still isn’t working after the upgrade to 0.34.0.1. I’ve created a new set of keys and invited you to them, but I don’t know how to update them in the Infrastructure section.

Thanks for letting me know. I'll take a look at next week. I suspect it should be an easy fix.

**Comment by benrfairless** [comment]
Thanks! If we could also consider adding these in:

CONTACT_FORM_RECAPTCHA: true
ENABLE_ANTI_SPAM: true
USER_CONTACT_FORM_RECAPTCHA: true
NEW_REQUEST_RECAPTCHA: true

I’m hoping this will stop spam emails we are getting through the site contact form and the many spam accounts we have that I need to go and clean up.

**Comment by mlandauer** [comment]
@benrfairless see #753

**Comment by mlandauer** [comment]
Upgraded to Ubuntu 18.04

**Comment by mlandauer** [comment]
Upgraded staging and production to Alaveteli 0.35.0.0. Running `rails geoip:download_data` didn't work because the domain geolite.maxmind.com didn't resolve. I assume that's because they've changed where their database lives since this Alaveteli release. I assume this will get addressed in more recent versions.

**Comment by mlandauer** [comment]
Upgraded staging and production to Alaveteli 0.36.0.2. Getting closer now

**Comment by mlandauer** [comment]
So close now. Upgraded in staging and production to Alaveteli 0.37.1.4. We now have the new versions of the geolite databases downloaded too as they now required a license key which is all set in the infrastructure setup (with Ansible).

**Comment by mlandauer** [comment]
We're now at Alaveteli 0.38.4.0 in production and staging! As of today that is the most recent released version. 🎉 

One change is that we've had to reintroduce the "gone_postal" state because of the way that's done internally. It's now not so straightforward to override. Also there appears to be a new bug in search highlighting. See #754. Also, we need to make a small change to go back to the way we used to do google analytics. See #755.

**Comment by mlandauer** [comment]
We've pretty much done all the work for this except for updating the help pages and launching it in production. So, closing this.

**Comment by mlandauer** [comment]
We haven't managed to update the help text to the level that I had hoped yet but otherwise everything on this is now done to the level that it's deployed to staging and we will do the final deploy to production tomorrow for the public launch of the new theme and Pro. So, I think it's fair to say that we can close this issue
