### ISSUE TITLE
"Personal Information" section doesn't work as expected

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#751]
We have something which automatically prompts users if they are requesting personal information after a specific period of time. 

It is supposed to prevent you from making a request if you answer "Yes" to the question "Are you asking for personal information that should be confidential?"

You are able to answer the question, but the request view is not hidden:

![image](https://user-images.githubusercontent.com/6841582/105124638-83496c00-5b15-11eb-8160-21d9c228ec8b.png)

**Comment by benrfairless** [comment]
Not sure if this is related to #749

**Comment by mlandauer** [comment]
> Not sure if this is related to #749

Undoubtedly it is. Thanks for spotting this. I'll try to get this fixed shortly.

**Comment by mlandauer** [comment]
Fixed by https://github.com/openaustralia/righttoknow/commit/a80b23fe5bd0baff01468068c24623f2d8c4a5be. There is another jquery loading problem on the same page which I'll try to fix separately.
