### ISSUE TITLE
Follow button on User Profile is very much larger than the text

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#756]
In test and production, find a user profile: https://www.righttoknow.org.au/user/matthew_landauer

The green "Follow" button is huge compared to other buttons:

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/6841582/106825992-ef54d400-66c0-11eb-8a40-b9da3e8e5389.png">

**Comment by benrfairless** [comment]
Might be fixed as part of #749 but raising it as a seperate issue just in case I forget.

**Comment by mlandauer** [comment]
Yes the design across the board is very likely to change with #749 so I won't prioritise fixing this in the short term. However, I won't close the issue in case the new design doesn't happen

**Comment by mlandauer** [comment]
This is what it looks like now in the new theme currently on staging:
![image](https://user-images.githubusercontent.com/2221/112075249-40b31700-8bcc-11eb-8d4d-251af2d81dc1.png)
