### ISSUE TITLE
update icon/logo for RTK

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#761]
The icon/logo for RightToKnow is based on the one from Chilean alevateli. Although it has served us well, it's time to refresh, without a white hand!  
Options are to adapt or lose entirely from the main landing page.

**Comment by benrfairless** [comment]
I really like just the text logo we have now. It's cleaner and more professional than the old one :)

**Comment by katska** [comment]
@benrfairless cool! It does feel better. @mlandauer Does this issue seem resolved to you? Have you documented the font and image creation files for later?

**Comment by mlandauer** [comment]
I'm going to leave this one open until the logo stuff is all done and dusted. There are some alternate versions to be made (for FB sharing and the html attachment view) and I want to test whether an SVG versions make the edges a little more crisp. (They look a little blurry and ill-defined for me)

**Comment by mlandauer** [comment]
The opengraph logos are now done.

There is still an issue with the display of attachements but a new issue has been opened for that (#803)
