### ISSUE TITLE
create new favicon

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#762]
When we update or lose the icon/logo for RightToKnow we'll need a matching favicon derived from the new thing, for easy tab finding in the browser.
dependent on #761

**Comment by katska** [comment]
first pass - round one!

![android-chrome-192x192](https://user-images.githubusercontent.com/1001129/112096116-cb5a3d00-8bf1-11eb-84ed-1302d633adf6.png)
![android-chrome-512x512](https://user-images.githubusercontent.com/1001129/112096125-cdbc9700-8bf1-11eb-8723-6a68d2df4a9c.png)
![favicon-16x16](https://user-images.githubusercontent.com/1001129/112096130-d01ef100-8bf1-11eb-906f-ad77b67a4775.png)
![favicon-32x32](https://user-images.githubusercontent.com/1001129/112096138-d1e8b480-8bf1-11eb-8a7f-38b39ab857a8.png)

**Comment by katska** [comment]
[favicon_io-2.zip](https://github.com/openaustralia/righttoknow/files/6186991/favicon_io-2.zip)

**Comment by katska** [comment]
also here https://drive.google.com/drive/u/1/folders/0AIx7lTJiGDqDUk9PVA

**Comment by mlandauer** [comment]
@katska I like except we're not using a round design element anywhere else so it feels a little out of place. Can we just go for a square in the colour instead?

**Comment by mlandauer** [comment]
Used the following settings:
![image](https://user-images.githubusercontent.com/2221/112096536-98647900-8bf2-11eb-939c-92c0ec50bc4e.png)

To make:
![android-chrome-192x192](https://user-images.githubusercontent.com/2221/112096506-84b91280-8bf2-11eb-97c8-67104546fe22.png)

**Comment by mlandauer** [comment]
Added in https://github.com/openaustralia/righttoknow/commit/f556bd31618dc650ccfe0e1cf15aea01f983adc5

It looks like the main favicon is working but at least the ios one (when adding to your homescreen) isn't working

**Comment by mlandauer** [comment]
Ah just a thought. I wonder if that might be related to the simple auth protecting the staging site

**Comment by mlandauer** [comment]
Temporarily disabled simple auth and now the ios icon works. So, I'm closing this
