### ISSUE TITLE
find and test landing page images

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#763]
Find some images options to test as RightToKnow front page backgrounds

https://docs.google.com/spreadsheets/d/1H4HGQZGuqK5Bh7oQG_Pe_MFMxjZ1JcAstl9yix2I1MU/edit?usp=sharing

**Comment by katska** [comment]
the one at WhatDoTheyKnow evokes internal large institutional structure, with people moving in it, inside a building. 
Possibilities are something similar, or something that's closer to the people making requests.

**Comment by mlandauer** [comment]
I think we've settled on an image for now
