### ISSUE TITLE
fix links broken on RTK/help/requesting

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#767]
Checking links at [w3c's link checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.righttoknow.org.au%2Fhelp%2Frequesting&hide_type=all&depth=&check=Check#results1), some of the links are broken on 
https://www.righttoknow.org.au/help/requesting
Specifically the section **Can you tell me more of the nitty gritty about the process of making requests? #**

http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/ redirected to https://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/ 404

 http://www.oaic.gov.au/freedom-of-information/foi-resources/freedom-of-information-fact-sheets/ redirected to https://www.oaic.gov.au/freedom-of-information/foi-resources/freedom-of-information-fact-sheets/
    Status: 301 -> 404 Not Found

http://www.ag.gov.au/RightsAndProtections/IntellectualProperty/Documents/StatementofIPprinciplesforAusGovagencies.pdf redirected to https://www.ag.gov.au/RightsAndProtections/IntellectualProperty/Documents/StatementofIPprinciplesforAusGovagencies.pdf
    Status: 301 -> 404 Not Found

 http://www.ombudsman.tas.gov.au/right_to_information/process
    Status: 404 Not Found

----
 https://twitter.com/righttoknowau
    Status: 400 Bad Request

    This is usually the sign of a malformed URL that cannot be parsed by the server. Check the syntax of the link.

**Comment by katska** [comment]
I checked the twitter account and that one is fine

**Comment by katska** [comment]
1) So the first link has been broken for a while - it was overall guidelines with lots of links and sections. https://web.archive.org/web/20140419053017/http://www.oaic.gov.au/freedom-of-information/applying-the-foi-act/foi-guidelines/
I think the equivalent is now https://www.oaic.gov.au/freedom-of-information/foi-guidelines/ There's also an overview for FOI practitioners to supply to Agency staff https://www.oaic.gov.au/freedom-of-information/guidance-and-advice/fact-sheet-for-foi-practitioners-to-provide-to-agency-staff/ (additional good info to include)?

**Comment by katska** [comment]
Tasmanian Ombudsman information page (last link) is now at https://www.ombudsman.tas.gov.au/right-to-information

**Comment by katska** [comment]
I found the [statement of IP principles ]( https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjl58WUmPDuAhXKQN4KHecRASIQFjABegQIAhAC&url=https%3A%2F%2Fwww.communications.gov.au%2Ffile%2F20151%2Fdownload%3Ftoken%3DnmvWmdrj&usg=AOvVaw3HCINU6jXoMqcoUxe-yZf5) again: that's dated 2016, I note a change of language from 'manage' in to 'protect' in sample of introductory text. https://www.communications.gov.au/search?search_api_views_fulltext=statement+of+IP+principles  - and there's a [2018 update ](https://www.communications.gov.au/documents/intellectual-property-principles-commonwealth-entities) and there is now a manual dated 2019.  I don't see any explanatory text about any changes made here. Since we first published it this may have changed.... it has also moved from Attorney General to Communications

**Comment by katska** [comment]
Copyright statement is 2016 on both. And indeed, they're essentially the same document, with formatting changes. One small but significant improvement is the link to creative commons licensing is no longer spelled out separately, its now embedded as a link in the text.
[ip_principles_for_commonwealth_entities_-_september_2016_0(1).pdf](https://github.com/openaustralia/righttoknow/files/5993498/ip_principles_for_commonwealth_entities_-_september_2016_0.1.pdf)

[intellectual-property-principles-for-commonwealth-entities.pdf](https://github.com/openaustralia/righttoknow/files/5993497/intellectual-property-principles-for-commonwealth-entities.pdf)

**Comment by katska** [comment]
All links found. Now to update them!

**Comment by mlandauer** [comment]
@katska I fixed the IP principles link in https://github.com/openaustralia/righttoknow/commit/d4064088cdf464ec7f6bddfcf459059c42a80e4e

**Comment by katska** [comment]
Changes all merged. Thanks @mlandauer! I rechecked the links and problems that showed up were all related to being on staging/password needed.

**Comment by mlandauer** [comment]
Woot! 🎉
