### ISSUE TITLE
New Theme - Yellow on white makes it hard to read some of the links

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#773]
The yellow on white background is very hard to see, especially when I've got Night Shift enabled. I think we should darken this a bit.

Example:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/6841582/108843856-3b3acf00-7616-11eb-9ab4-ffae70b4f2b4.png">

**Comment by mlandauer** [comment]
Thanks for actually creating some test requests and authorities on staging to show up the problem

**Comment by mlandauer** [comment]
So now links in incoming emails are styled the same as all the other links. Also decided to switch the download links (in the attachments) to be gray. If the link has been visited it's blue again which is a bit weird but that appears to be the same behaviour as whatdotheyknow.
