### ISSUE TITLE
Review Pro email templates

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/righttoknow#796]
Because we haven't checked that they all make sense for our context

**Comment by mlandauer** [comment]
Here are places to look:
* https://github.com/mysociety/alaveteli/tree/develop/app/views/alaveteli_pro/account_mailer
* https://github.com/mysociety/alaveteli/tree/develop/app/views/alaveteli_pro/embargo_mailer
* https://github.com/mysociety/alaveteli/tree/develop/app/views/alaveteli_pro/metrics_mailer
* https://github.com/mysociety/alaveteli/tree/develop/app/views/alaveteli_pro/subscription_mailer
* https://github.com/mysociety/alaveteli/tree/develop/app/views/alaveteli_pro/webhook_mailer

**Comment by katska** [comment]
The wording looks good to me. I don't see any issues from the perspective of UK > Aus or wording that looks odd. There are links out to stripe payment that I'll assume work, or that are tested elsewhere.

**Comment by mlandauer** [comment]
Looks done then
