### ISSUE TITLE
Send out teaser Tweets 

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/righttoknow#799]
"something exciting is coming next week"

**Comment by katska** [comment]
a document is ready here https://drive.google.com/drive/u/1/folders/0AIx7lTJiGDqDUk9PVA

**Comment by katska** [comment]
Using https://favicon.io/favicon-generator/ with 

Zilla Slab | #ffffff | #25d9ed 
Font FG.BG colours

as a first pass 

Also uploaded to https://drive.google.com/drive/u/1/folders/0AIx7lTJiGDqDUk9PVA in favicon_io-2 folder
[about.txt](https://github.com/openaustralia/righttoknow/files/6186961/about.txt)
![android-chrome-512x512](https://user-images.githubusercontent.com/1001129/112095497-b6c97500-8bf0-11eb-990c-4655d7ec19c7.png)
![android-chrome-192x192](https://user-images.githubusercontent.com/1001129/112095503-b8933880-8bf0-11eb-81f2-4d00de65e7c5.png)

**Comment by katska** [comment]
https://twitter.com/RightToKnowAu/status/1374228704503627783

**Comment by mlandauer** [comment]
Done
