### ISSUE TITLE
offer discount to MEAA for RightToKnow Pro

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#802]
We want to offer a discount to the MEAA members
Maybe the want to be a supporting org?

I've messaged them today on fb. https://www.facebook.com/withMEAA

**Comment by katska** [comment]
I've messaged them via facebook

**Comment by mlandauer** [comment]
We were recommended to offer this to Walkley Foundation instead. Fingers crossed we'll get something in their newsletter going out Thursday.

**Comment by mlandauer** [comment]
Was included in the Walkley newsletter. See https://mailchi.mp/7860bf2e2aa7/apr-08-2021-walkley-newsletter?e=334e10f109
