### ISSUE TITLE
fix mobile usability reported by google

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#812]
We received the following:

Mobile Usability issues detected on righttoknow.org.au

To the owner of righttoknow.org.au:

Search Console has identified that your site is affected by 1 Mobile Usability issues:

Top Issues

The following issues were found on your site:

Viewport not set

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**fix mobile useability** [](issues](https://search.google.com/search-console/not-verified?original_url=/search-console/mobile-usability/drilldown?resource_id%3Dsc-domain:righttoknow.org.au%26item_key%3DCAY%26utm_source%3Dwnc_10030322%26utm_medium%3Dgamma%26utm_campaign%3Dwnc_10030322%26utm_content%3Dmsg_100058679%26hl%3Den&original_resource_id=sc-domain:righttoknow.org.au&hl=en))

**Comment by benrfairless** [comment]
Page Experience Report in Search Console says that mobile is all good. Closing this out.
