### ISSUE TITLE
following 'confirm email address' link returns reCAPTCHA error

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#819]
Someone reported an error  at the email confirmation stage: 
"Please click on the link below to confirm your email address. Then your FOI request to Queensland Health will be sent and published."
I tried to click through for them and get this error 
"There was an error with the reCAPTCHA. Please try again."

<img width="1090" alt="Screenshot 2023-07-18 at 12 01 58 pm" src="https://github.com/openaustralia/righttoknow/assets/1001129/8d1c4969-814c-4927-a0a6-05dc014d98bb">

**Comment by benrfairless** [comment]
This was raised in 2023, and people have been able to create accounts since. I am going to close this as no longer an issue.
