### ISSUE TITLE
check for missing authority email addresses

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#820]
Find missing FOI email for these public authorities (try phoning!)

**Found and updated** 
Australian Hearing
Australian Pesticides and Veterinary Medicines Authority
Commonwealth Scientific and Industrial Research Organisation
NSW Fluoridation of Public Water Supplies Advisory Committee - under Health - no specific address
NSW Medical Services Committee - under Health also
Rice Marketing Board for the State of NSW

Not Found:
NSW Fire Services Joint Standing Committee (RFS)
NSW Bush Fire Coordinating Committee (RFS)
NSW Civil and Administrative Tribunal
Minister for Early Childhood and Child Care - specific address for ministry not found
Minister Assisting for School Education - specific address for ministry not found
Central Coast Regional Organisation of Councils (CCROC) - not found
NSW Poisons Advisory Committee - unable to find a website for them - a search takes me to service NSW so added their email address. Good place to start if someone has a GIPA request.
NSW Universities Admissions Centre - nothing here https://www.uac.edu.au/about/contact - EDU?

**Defunct?**
Ministerial Advisory Committee on AIDS, Sexual Health and Hepatitis - I can find no mention of this one
Pathology Consultative Committee

**Defunct**
Office of the Fair Work Building Industry Inspectorate
https://en.wikipedia.org/wiki/Fair_Work_Building_and_Construction

**Not looked for yet:**
Southern NSW Local Health District - NSW Health?
Western NSW Local Health District- NSW Health?
TAFE SA
 Gerard Community Council	
 Yalata Community
 NSW Department of Premier and Cabinet	
 NSW Department of Primary Industries

**Comment by benrfairless** [comment]
These are located in the summary page of Right to Know - I am going to close this out to avoid duplication, please feel free to re-open if you disagree.
